### ISSUE TITLE
Error 1118: Row size too large

### ISSUE THREAD

**Issue by designstorming** [drone/drone#2564] opened 2019-01-01 12:55 UTC
```drone:
    container_name: dsci-drone
    image: 'drone/drone:1.0.0-rc.3'
    restart: always
    hostname: drone.dev
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './data/drone:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always
    environment:
      - 'DRONE_GITEA_SERVER=http://100.100.100.3:3000'
      - 'DRONE_GITEA_SKIP_VERIFY=false'
      - 'DRONE_GIT_ALWAYS_AUTH=false'
      - 'DRONE_RUNNER_CAPACITY=2'
      - 'DRONE_SERVER_HOST=100.100.100.4'
      - 'DRONE_SERVER_PROTO=http'
      - 'DRONE_TLS_AUTOCERT=false'
      - 'DRONE_ADMIN=milan'
      - 'DRONE_OPEN=true'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
      - 'MYSQL_DATABASE=drone'
      - 'DRONE_DATABASE_DRIVER=mysql'
      - 'DRONE_DATABASE_DATASOURCE=drone:drone@tcp(100.100.100.2:3306)/drone?parseTime=true'
    networks:
      gitea:
        ipv4_address: 100.100.100.4
```

Everything works except when I try to change database provider from sqlite to mysql. It throws an error that some column type needs to be changed from varchar/blob to text.

Also, how do I add volume to be trusted. All docs I have been over through have different answers which does not work in this version of drone drone/drone:1.0.0-rc.3 (docker)

**Comment by bradrydzewski** [comment] 2019-01-01 17:44
Hi there, we are testing 1.0.0-rc with the following mysql image and configuration and are unable to reproduce any issues:

```
docker run \
  -p 3306:3306 \
  --env MYSQL_DATABASE=test \
  --env MYSQL_ALLOW_EMPTY_PASSWORD=yes \
  --name mysql \
  --detach \
  --rm \
  mysql:5
```

Can you please provide a `docker run` command that can be used to reproduce the issue?

**Comment by designstorming** [comment] 2019-01-01 19:45
I used docker compose which I copied from the bash script I wrote (only different network ips). Here it is in it's full:

### Network
```
docker network create \
  --driver=bridge \
  --subnet=172.172.0.0/16 \
  --ip-range=172.172.7.0/24 \
  --gateway=172.172.7.254 \
gitea
```
### MySql
```
docker run -d \
  --name=mysql-test \
  --env=MYSQL_ROOT_PASSWORD=pw \
  --env=MYSQL_DATABASE=gitea \
  --env=MYSQL_USER=user \
  --env=MYSQL_PASSWORD=pw \
  --net=gitea \
  --ip=172.172.7.172 \
  --publish=3306:3306 \
  --volume=/abs-path/mysql-data:/var/lib/mysql \
mysql:latest
```
### Gitea
```
docker run -d \
  --name=gitea-test \
  --net=gitea \
  --ip=172.172.7.173 \
  --publish=3000:3000 \
  --volume=/abs-path/git-repository:/data/git/repositories \
gitea/gitea:latest
```
### Drone
```
DRONE_GITEA_SERVER="http://172.172.7.173:3000"
DRONE_SERVER_HOST="172.172.7.174"
DRONE_SERVER_PROTO="http"
docker run \
   --privileged=true \
   --net=gitea \
   --ip=172.172.7.174 \
   --volume=/var/run/docker.sock:/var/run/docker.sock \
   --volume=/abs-path/drone:/data \
   --env=DRONE_GITEA_SERVER=$DRONE_GITEA_SERVER \
   --env=DRONE_GIT_ALWAYS_AUTH=false \
   --env=DRONE_RUNNER_CAPACITY=2 \
   --env=DRONE_SERVER_HOST=$DRONE_SERVER_HOST \
   --env=DRONE_SERVER_PROTO=$DRONE_SERVER_PROTO \
   --env=DRONE_TLS_AUTOCERT=false \
   --publish 80:80 \
   --publish 443:443 \
   --restart=always \
   --detach=true \
   --name=drone-test \
   drone/drone:1.0.0-rc.3
```

**Comment by tboerger** [comment] 2019-01-06 18:36
You should never use latest mysql or gitea images. Mysql can anytime break with major version upgrades, and gitea latest is based on the master branch and can also break at any time.

**Comment by bradrydzewski** [comment] 2019-01-06 18:47
I think we can close this issue.  I just ran the full test suite against `mysql:5` and `mysql:8` and was unable to reproduce any database errors. I would suggest moving any further questions you have to our mailing list at https://discourse.drone.io.

**Closed by bradrydzewski** 2019-01-06 18:47 UTC
