### ISSUE TITLE
cannot find re-activate/deactivate button on web ui

### ISSUE THREAD

**Issue by depay** [drone/drone#1109] opened 2015-07-24 03:25 UTC
I remove webhooks from gitlab by mistake, and i want to re-activate a project to re-create the hook intead of creating it on gitlab by myself... So i have to do that though api, that's really inconvenient..

That also happends if drone host:port changes without changing DB.

**Comment by chengweiv5** [comment] 2015-08-07 03:45
could you try to use the API to activate it again? http://readme.drone.io/api/repos/post/, to ensure it the API works.

```
curl -X POST "https://drone.io/api/repos/github.com/foo/bar?access_token=<your token>"
```

**Comment by depay** [comment] 2015-08-08 12:46
I've tried and it worked. What i meant above is nothing but *inconvenient*.

**Comment by bradrydzewski** [comment] 2015-08-18 19:35
duplicate of #523

**Closed by bradrydzewski** 2015-08-18 19:35 UTC

**Comment by hiroshi** [comment] 2016-07-11 12:41
drone:0.4

I tried following request, but the webhook didn't appear.
```
curl -X POST "https://drone.myhost.com/api/repos/my/repo?access_token=$DRONE_TOKEN
...
< HTTP/1.1 409 Conflict
...
Repository already exists.
```
