### ISSUE TITLE
[Feature] Drone jobs for individual subdirectories in a repo

### ISSUE THREAD

**Issue by mellena1** [drone/drone#2490] opened 2018-09-13 15:36 UTC
Hi all,

I was wondering if a feature to have multiple Drone jobs for a single repository was possible at some point in the future. We have a large repo with multiple infrastructure related Jenkins jobs, and ideally we would like to move them to Drone. Right now with Jenkins we trigger them off of a push to the repo and Jenkins has a plugin to check if a specific subdirectory/specific files had changed at all in that commit.

I could see this working as having one main .drone.yml file in the root of the directory, and in that file having some sort of syntax like:
```yaml
pipeline:
  mydir-job:
    image: plugins/run-another-file
    file-to-run: mydir/.drone.yml
    when:
      changed-files:
      - mydir/*
      - thisdir/myfile
```

I have considered writing a plugin for looking for changed files in a commit, but as far as I have found, drone does not have any sort of call to execute a specific drone file.

I have read that this wasn't included originally because of how drone is triggered based off of repo-level events, but I could see this being a useful addition to the platform.

Interested to hear your thoughts. Thanks.

**Comment by tboerger** [comment] 2018-09-13 15:47
Thank you for the request, but this is a duplicate of https://github.com/drone/drone/issues/1021

**Closed by tboerger** 2018-09-13 15:47 UTC

**Comment by mellena1** [comment] 2018-09-13 15:54
Awesome, thanks! Sorry for the duplicate. I looked through the open issues trying to find an existing thread, but I must have missed that one!

**Comment by bradrydzewski** [comment] 2018-09-13 15:54
also see my comment here:
https://github.com/drone/drone/issues/1021#issuecomment-417819643

the next version of drone introduces a plugin hook for the yaml.  In my comment I provide a link to a starter project that you can use to create a yaml plugin. There is no documentation yet since the feature is new and 0.9 is not released, but I'm happy to answer some questions in the discourse forum.

**Comment by mellena1** [comment] 2018-09-13 15:59
Awesome, thanks!
