### ISSUE TITLE
[0.4] Drone repo page responds with 404 instead of 403

### ISSUE THREAD

**Issue by Jean85** [drone/drone#1465] opened 2016-02-05 10:46 UTC
I'm using GitLab login integration. I have a browser bookmark pointed to Drone's repo page. When the login fails, Drone responds with a 404 (not found) instead of a 403 (Unauthorized) or (better) redirecting to the login page, as it happens if I open Drone's homepage.

**Comment by gtaylor** [comment] 2016-02-05 18:11
Looks like a dupe of #1266.

**Comment by bradrydzewski** [comment] 2016-02-05 18:15
closing as duplicate, please subscribe to #1266

**Closed by bradrydzewski** 2016-02-05 18:15 UTC
