### ISSUE TITLE
Drone doesn't see the GitHub private repo

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [drone/drone#1384] opened 2015-12-23 07:20 UTC
I'm an admin of the private fork but I don't see it in the repositories list and it produces "Not found" with the direct link.

**Comment by bradrydzewski** [comment] 2015-12-23 16:50
there are three possible root causes here

1. you are not logged in. Similar to GitHub drone shows a 404 if the repository is private and you are not authenticated in order to avoid leaking data
2. your organization needs to grant access to Drone. see the below screenshot
3. there is a known issue (I don't have the reference issue number, but I know one exists) where in current version of Drone we cache the repository list for 24 hours. If you directly visited the page, however, and got a not found this is probably not the issue

<img width="758" alt="screen shot 2015-12-08 at 3 23 59 pm" src="https://cloud.githubusercontent.com/assets/817538/11980746/1163c330-a96b-11e5-87e3-2f07bd0ed2b4.png">

**Comment by Ilya-Kuchaev** [comment] 2015-12-24 06:35
These are not a cases. All the other repositories are working. But not this one. And I really can't say why. How could I debug such errors inside the Docker container? And do you have any plans to create some dev tag (docker) for the latest changes?

**Comment by bradrydzewski** [comment] 2015-12-24 06:45
@Ilya-Kuchaev my advice is to restart Drone to flush the cache. Then make sure you are logged into Drone and go to `http://my-drone-instance.com/api/user/repos/remote` in your browser to list every repository in GitHub. This uses the GitHub API to list all repositories, and does not implement any logic to filter the list.

**Comment by Ilya-Kuchaev** [comment] 2015-12-25 10:01
That's strange.
It shows all our private forks but not this one. What settings could I change to resolve such issues?

**Comment by bradrydzewski** [comment] 2015-12-25 19:22
did you try both of my above suggestions? what were the specific results for each?

**Comment by bradrydzewski** [comment] 2016-03-15 01:11
closing because we could not re-produce with the latest version

**Closed by bradrydzewski** 2016-03-15 01:11 UTC
