### ISSUE TITLE
How to use Drone with self-hosted git repository

### ISSUE THREAD

**Issue by vitalik** [drone/drone#2552] opened 2018-12-12 08:55 UTC
I've been searching and asking forums about this:

is it possible to use Drone with self-hosted git repositories  (**without** GitHub or GitLab) ?

**Comment by jhasse** [comment] 2018-12-12 10:45
Yes. Use Gitea and see https://docs.drone.io/installation/gitea/. Btw: You can also self-host GitLab.

**Comment by vitalik** [comment] 2018-12-12 12:30
well my question is about the case when I have git repo **WITHOUT** gittea, gitlab, github

just bare repository accessible only over ssh

**Comment by apricote** [comment] 2018-12-12 12:35
This is not possible because Drone uses the SCM provider for user managment. Also SCM provider webhooks are used to trigger the builds.

**Comment by vitalik** [comment] 2018-12-12 12:39
can you please explain a little bit the flow ?

does Drone periodically  checks some  external API to find new code pushes ?

Or it's other way around  - a SCM provider "notifies" Drone to trigger build ?

**Comment by apricote** [comment] 2018-12-12 12:43
You can check out the full interface at https://github.com/drone/go-scm/tree/master/scm

When you activate a Repository in Drone, Drone will use the `go-scm` drivers to create Webhooks in your SCM Provider. The SCM Provider will call the webhooks when new events happen (push, tag, pr created...) and Drone will create a new Job.

**Comment by bradrydzewski** [comment] 2018-12-12 16:47
closing as duplicate of https://github.com/drone/drone/issues/10

**Closed by bradrydzewski** 2018-12-12 16:47 UTC
