### ISSUE TITLE
GitHub Enterprise - cannot authenticate user. Error retrieving user or verified email. No verified Email address for GitHub account

### ISSUE THREAD

**Issue by Telmo** [drone/drone#1513] opened 2016-03-03 12:37 UTC
This is in reference to https://discuss.drone.io/t/github-enterprise-configuration/187

Drone requires the email address to be verified, but GitHub Enterprise does not have email verification:

This is the email response from github support when I raised the issue:

```

Hi Roberto,

Email verification is not enabled on GitHub Enterprise. That is expected behaviour. You'll notice that our Verifying your email address help article deliberately does not target any GitHub Enterprise releases.

Any integrations that expect email verification to be enabled on GitHub Enterprise installations will not work, and should not be expected to work. Such integrations will need to be modified in order to work correctly on GitHub Enterprise.

I hope that's clear.

Thanks,
```

**Comment by bradrydzewski** [comment] 2016-03-03 16:31
I'm closing this because drone does not require email verification for GitHub Enterprise. We have special logic for GitHub Enterprise that chooses the very first email address in the list:

```
	// WARNING, HACK
	// for out-of-date github enterprise editions the primary
	// and verified fields won't exist.
	if !strings.HasPrefix(*user.HTMLURL, DefaultURL) && len(emails) != 0 {
		user.Email = emails[0].Email
		return user, nil
	}
```

I can confirm we have a large number of GitHub Enterprise installations for Drone and this logic is working well. I recommend contacting GitHub to see why the `/user/emails` endpoint is returning an empty list for your account

**Closed by bradrydzewski** 2016-03-03 16:31 UTC
