### ISSUE TITLE
more options to privileged mode

### ISSUE THREAD

**Issue by fommil** [drone/drone#1046] opened 2015-06-05 19:48 UTC
I would like to run some docker images with escalated privileges on a few devices (e.g. GPU), but not everything (e.g. the hard drive!). It is possible to be this fine-grained with docker on the command line but there is currently no option to enter the commands via drone.

**Comment by bradrydzewski** [comment] 2015-06-05 19:49
dupe of https://github.com/drone/drone/issues/849

**Closed by bradrydzewski** 2015-06-05 19:49 UTC
