### ISSUE TITLE
Bitbucket endpoint not displaying all repositories

### ISSUE THREAD

**Issue by mastertinner** [drone/drone#1667] opened 2016-06-08 12:55 UTC
I have a Drone instance connected to Bitbucket. It somehow doesn't list all repos I have access to. I can see all repos which I or one of my groups is the owner of but I cannot see a project which I am not the owner of in the Drone UI. I am Admin of said repo.

**Comment by bradrydzewski** [comment] 2016-06-08 18:06
I am unable to reproduce, so will need more detailed debugging from your end

Drone will cache the repository list for anywhere from 30 minutes (in newer versions) to 24 hours (in older versions) which means newly created repositories may take time to display in the list. But otherwise drone uses the standard bitbucket endpoints with no modification to display user and team repos:

* https://confluence.atlassian.com/bitbucket/repositories-endpoint-423626330.html#repositoriesEndpoint-GETalistofrepositoriesforanaccount
* https://confluence.atlassian.com/bitbucket/repositories-endpoint-423626330.html#repositoriesEndpoint-GETalistofrepositoriesforateam

**Comment by mastertinner** [comment] 2016-06-09 06:32
Thanks for the quick reply, @bradrydzewski. That is exactly the problem. The endpoints you describe only show resources I own or which are owned by a team of mine. However, I would like to see all the repos I have admin access to because that is all I need to set the webhooks. I would suggest to use the `https://api.bitbucket.org/2.0/repositories?role=admin` endpoint instead.

**Comment by bradrydzewski** [comment] 2016-06-09 06:37
so just so I fully understand, `api.bitbucket.org/2.0/repositories` does not include repos where your role is admin? We can't use `role=admin` because then users with read or write access would no long see repos in their feed. What about `role=member`?

**Comment by bradrydzewski** [comment] 2016-06-09 06:42
cc @gtaylor I know you use (used) bitbucket. Is this something you can advise on?

**Comment by mastertinner** [comment] 2016-06-09 06:58
`=member` does indeed include all repos where the user has read, write, admin and owner rights. I used the `=admin` because I thought that Drone requires admin permissions to set the webhooks but if member is sufficient, then even better.

If you look at the description of the endpoint that you posted above, you'll see that it only lists repos where the user is owner since the URL of the endpoint is described as `https://api.bitbucket.org/2.0/repositories/{owner}`

**Comment by bradrydzewski** [comment] 2016-06-09 07:04
ok thanks for clarifying! We can replace with `https://api.bitbucket.org/2.0/repositories?role=member` which seems to be an improvement over how we get this list today, fetching many different lists per org and user and combining at runtime. This should result in far less API calls.

> I thought that Drone requires admin permissions to set the webhooks but if member is sufficient,

This is true, although we use the repository list for a few different purposes. This includes generating your build feed which takes the intersection of all repositories in Drone and all your repositories in Bitbucket.

**Comment by mastertinner** [comment] 2016-06-09 08:12
Ok, cool. That sounds perfect. Let me know if I can help in any way.

**Comment by gtaylor** [comment] 2016-06-09 17:07
I hadn't seen this behavior in the past, but I'm about two months out of date on Bitbucket and Drone+Bitbucket. Plus, that was 0.4.

It looks like you may have figured something out, though.

**Comment by developersbs** [comment] 2016-12-12 23:40
I see the similar issue for Github. I can't get the repository list which I have admin access to. Can anyone confirm whether this is an issue?

**Comment by bradrydzewski** [comment] 2016-12-13 00:29
this issue is specific to the Bitbucket API and would not impact GitHub. It is most likely due to the organization owning your repository restricting third party applications. I added a note to the StackOverflow question
http://stackoverflow.com/questions/41110945/how-to-get-the-github-repository-in-drone-io

**Comment by bradrydzewski** [comment] 2018-07-03 18:09
this has been addressed in our support library, and the change will land in 0.9. For those interested you can take a look here https://github.com/drone/go-scm/blob/master/scm/driver/bitbucket/repo.go#L88

once a release candidate is available we will close this issue

**Comment by bradrydzewski** [comment] 2018-11-08 00:54
fixed in 1.0.0-rc.1

**Closed by bradrydzewski** 2018-11-08 00:54 UTC
Labels: in-progress, vcs/bitbucket

**Comment by bradrydzewski** [comment] 2018-11-26 21:04
@nathan-fps I am not sure. There was a thread in discourse that mentioned an issue with > 100 repositories [1] but I don't have an account with > 100 repositories to test with. If you are open to looking at the pagination code it is posted [here](https://github.com/drone/go-scm/blob/master/scm/driver/bitbucket/repo.go#L87) [2]. Let me know what you see. Thanks!

[1] https://discourse.drone.io/t/1-0-0-rc-1-drone-repository-filter-not-respected-for-bitbucket/3023
[2] https://github.com/drone/go-scm/blob/master/scm/driver/bitbucket/repo.go#L87

**Comment by nathan-fps** [comment] 2018-11-26 21:42
@bradrydzewski Yup that is exactly the same issue. I have only 100 repositories synced. I'll open a more specific issue on the topic and take a look at the `go-scm` implementation to see if I can reproduce the issue there.
