### ISSUE TITLE
Sync Gitlab project in subgroups KO

### ISSUE THREAD

**Issue by perriea** [drone/drone#2711] opened 2019-05-18 21:14 UTC
**drone-server version:** 1.1.0

When you try to access/activate on Gitlab sub-group project, the Ui and the API respond 404:
```
{"admin":false,"error":"404 Project Not Found","level":"warning","msg":"api: cannot sync repository permissions","name":"google-bigquery","namespace":"big-data","read":true,"request-id":"1LQI7ZKlhBuO0DPfbOC05ePj9rn","time":"2019-05-18T21:08:48Z","user.login":"perriea","write":false}
```

**Example :**
Group => Group => Project 👎 
Group => Project 👍 
User => Project 👍 

I tried to put more rights on the application Gitlab but without success. I think it's a regression ...

**Comment by tboerger** [comment] 2019-05-19 17:55
It's not a regression, sub groups never worked with Drone as this has never been integrated.

There should be already closed issues which include the reasoning behind it.

**Comment by bradrydzewski** [comment] 2019-05-19 18:14
duplicate of https://github.com/drone/drone/issues/2009

**Closed by bradrydzewski** 2019-05-19 18:14 UTC
