### ISSUE TITLE
Builds in drone 0.5.0 fail with exit code 255

### ISSUE THREAD

**Issue by gdubicki** [drone/drone#1653] opened 2016-05-23 20:44 UTC
My builds in drone 0.5.0 (I used docker image with this tag) failed `with exit code 255`. I have tried building in 2 different repos, with different drone.yml.

During one of the failures my `drone.yml` looked like this, for example:

```
pipeline:
  build_test:
    image: node:5.3.0
    commands:
      - npm install
      - npm test
```

My drone server logged this:
```
time="2016-05-23T08:21:24Z" level=info msg="Starting build gdubicki/drone-test#1.1"
time="2016-05-23T08:21:27Z" level=info msg="Finished build gdubicki/drone-test#1.1"
```

...and things like:

```
time="2016-05-20T13:33:52Z" level=error msg="Error #01: sql: no rows in result set\n" ip=164.40.242.212 latency=735.742µs method=GET path="/api/repos/gdubicki/drone-test/logs/1/1" status=404 time="2016-05-20T13:33:52Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
```

...when viewing build status page.

I have also found this in my syslog, logged by docker engine:

```
May 23 08:21:25 drone01 docker: time="2016-05-23T08:21:25.104726153Z" level=error msg="Handler for GET /v1.15/images/plugins/:latest/json returned error: No such image: plugins/:latest"
May 23 08:21:25 drone01 docker: time="2016-05-23T08:21:25.106595561Z" level=error msg="Handler for POST /v1.15/images/create returned error: Error parsing reference: \"plugins/:latest\" is not a valid repository/tag"
May 23 08:21:25 drone01 docker: time="2016-05-23T08:21:25.107794570Z" level=error msg="Handler for POST /v1.15/containers/create returned error: Error parsing reference: \"plugins/:latest\" is not a valid repository/tag"
May 23 08:21:26 drone01 docker: time="2016-05-23T08:21:26.108810047Z" level=info msg="Container 479d49b1e7ad5210cc3c38e04fe9326173ab758fd2a016135b3ea347df352658 failed to exit within 1 seconds of signal 15 - using the force"
May 23 08:21:26 drone01 docker: time="2016-05-23T08:21:26.138603084Z" level=warning msg="container 479d49b1e7ad5210cc3c38e04fe9326173ab758fd2a016135b3ea347df352658 restart canceled"
```

(gitter chat link: https://gitter.im/drone/drone?at=5742d01edce4845b35ec4913)

**Comment by bradrydzewski** [comment] 2016-05-23 20:55
closing as I am unable to reproduce using the latest version of drone and the drone agent from master

**Closed by bradrydzewski** 2016-05-23 20:55 UTC
