### ISSUE TITLE
Gitlab 'merged' webhook is ignored

### ISSUE THREAD

**Issue by sheinbergon** [drone/drone#2776] opened 2019-08-05 14:45 UTC
Assessing the new `action` added in this issue [issue](https://github.com/drone/drone/issues/2685) condition, it seems like `merged` webhooks (hooks firing from gitlab when the repository is merged ) are ignored in drone. 

That means:
- The repository is properly integrated with drone
- Hooks are fired and a 200 response is received from drone.
- Drone logs show no recollection of handling the `merged` hook (as opposed to `opened` hooks, which are properly evaluated)
- Using debug logging, I get this message:
```
{"fields.time":"2019-08-05T14:37:51Z","latency":625401,"level":"debug","method":"POST","msg":"","remote":"172.18.0.1:37804","request":"/hook","request-id":"1P0fKgKxws4QTAmMxVIWV23bHJY","time":"2019-08-05T14:37:51Z"}
```
I have specific interest to act on this merged event, rather then use the push event fired on the target branch.

Any help will be much advised.

**Comment by bradrydzewski** [comment] 2019-08-05 15:07
This is by design. When you merge a pull request gitlab triggers a push hook. Drone ignores the merged hook and instead uses the push hook. This ensures Drone behaves the same across all providers (github, gitlab, gogs, gitea, etc). If we enabled merge hooks it would result in two builds for every merge, which the majority of users would consider a bug.

**Comment by sheinbergon** [comment] 2019-08-05 15:13
Thank you for your prompt response. Shouldn't this for the very least be turned off by default but settable by the user? using the new `actions` feature, I can now discern a 'merged' event, which gives me more details (such as source branch) as opposed to a master branch push.

Is there any possibility you might consider changing this behavior?

**Comment by bradrydzewski** [comment] 2019-08-05 15:23
> Shouldn't this for the very least be turned off by default but settable by the user? using the new actions feature, I can now discern a 'merged' event, which gives me more details

Yes, we hope to support additional actions in the future and I have described something similar [here](https://github.com/drone/drone/issues/1878#issuecomment-287598789). We have an existing issue that addresses this request. Lets consolidate and track this at https://github.com/drone/drone/issues/1878

**Closed by bradrydzewski** 2019-08-05 15:23 UTC
