### ISSUE TITLE
Show errors on webhooks in user interface

### ISSUE THREAD

**Issue by Alber70g** [drone/drone#2010] opened 2017-04-21 14:34 UTC
I had a wrong indent in my .drone.yml. This resulted in a very unclear HTTP 400 response from Drone on my webhook in Bitbucket. 

I can figure 2 solutions:  
- either add the error to the HTTP 400 response 
- or show an attempted build in the user interface of Drone with what's going on

**Comment by bradrydzewski** [comment] 2017-04-21 15:39
duplicate of https://github.com/drone/drone/issues/672

**Closed by bradrydzewski** 2017-04-21 15:39 UTC
