### ISSUE TITLE
Drone is throwing up 500 on tag hooks for Gogs

### ISSUE THREAD

**Issue by cusspvz** [drone/drone#1412] opened 2016-01-13 02:23 UTC
Drone is throwing up an 500 error whenever a tag hook is triggered by gogs.

`versions`
```
Drone 0.4.0
Gogs 0.8.10
```

`tag payload`
```json
{
  "secret": "hidden",
  "ref": "v1.2.6",
  "ref_type": "tag",
  "repository": {
    "id": 1,
    "name": "repository",
    "url": "https://gogs.company.com/project/repository",
    "ssh_url": "git@gogs.company.com:project/repository.git",
    "clone_url": "https://gogs.company.com/project/repository.git",
    "description": "",
    "website": "",
    "watchers": 13,
    "owner": {
      "name": "project",
      "email": "",
      "username": "project"
    },
    "private": true
  },
  "sender": {
    "login": "jose.moreira",
    "id": 1,
    "avatar_url": "https://gogs.company.com//avatar/6b2f1bb07eb368151c88af45764967df"
  }
}
```

`branch payload`
```json
{
  "secret": "hidden",
  "ref": "refs/heads/master",
  "before": "4d160779370bb6c974adb558b68d3703a1fa7059",
  "after": "a42e1bb384efffcc0d994a9c0e451e20d1ee61c9",
  "compare_url": "https://gogs.company.com/project/repository/compare/4d160779370bb6c974adb558b68d3703a1fa7059...a42e1bb384efffcc0d994a9c0e451e20d1ee61c9",
  "commits": [
    {
      "id": "a42e1bb384efffcc0d994a9c0e451e20d1ee61c9",
      "message": "Drone: fix yml\n",
      "url": "https://gogs.company.com/project/repository/commit/a42e1bb384efffcc0d994a9c0e451e20d1ee61c9",
      "author": {
        "name": "José Moreira",
        "email": "hidden",
        "username": "jose.moreira"
      }
    }
  ],
  "repository": {
    "id": 1,
    "name": "repository",
    "url": "https://gogs.company.com/project/repository",
    "ssh_url": "git@gogs.company.com:project/repository.git",
    "clone_url": "https://gogs.company.com/project/repository.git",
    "description": "",
    "website": "",
    "watchers": 13,
    "owner": {
      "name": "project",
      "email": "",
      "username": "project"
    },
    "private": true
  },
  "pusher": {
    "name": "jose.moreira",
    "email": "hidden",
    "username": "jose.moreira"
  },
  "sender": {
    "login": "jose.moreira",
    "id": 1,
    "avatar_url": "https://gogs.company.com//avatar/6b2f1bb07eb368151c88af45764967df"
  }
}
```

@bradrydzewski any idea why?

**Comment by bradrydzewski** [comment] 2016-01-13 02:53
please check `docker logs drone` to see what the error is in the log file

**Comment by cusspvz** [comment] 2016-01-13 03:03
Here it is:

```
13/01/2016 03:03:012016/01/13 03:03:01 Panic recovery -> runtime error: index out of range
13/01/2016 03:03:01/usr/local/go/src/runtime/panic.go:423 (0x4b8c29)
13/01/2016 03:03:01/usr/local/go/src/runtime/panic.go:12 (0x4b7109)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/remote/gogs/helper.go:75 (0x63c317)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/remote/gogs/gogs.go:234 (0x63b8f7)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/controller/hook.go:28 (0x660be1)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/router/middleware/token/token.go:17 (0x675ade)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/router/middleware/cache/perms.go:22 (0x4fed86)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/router/middleware/session/user.go:64 (0x675613)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/router/middleware/context/context.go:31 (0x500276)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/router/middleware/context/context.go:20 (0x5000e6)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/router/middleware/context/context.go:13 (0x4fff43)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/router/middleware/cache/cache.go:12 (0x4ff7e3)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/router/middleware/header/header.go:58 (0x500d81)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/router/middleware/header/header.go:26 (0x50096c)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/router/middleware/header/header.go:18 (0x5007e0)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/router/middleware/location/location.go:15 (0x671898)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/logger.go:56 (0x6575d1)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/recovery.go:43 (0x658131)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/context.go:95 (0x64612a)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/gin.go:294 (0x64cb82)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/vendor/github.com/gin-gonic/gin/gin.go:275 (0x64c7b7)
13/01/2016 03:03:01/drone/src/github.com/drone/drone/router/router.go:183 (0x4fdf4b)
13/01/2016 03:03:01/usr/local/go/src/net/http/server.go:1422 (0x5f9cda)
13/01/2016 03:03:01/usr/local/go/src/net/http/server.go:1862 (0x5fc15e)
13/01/2016 03:03:01/usr/local/go/src/net/http/server.go:1361 (0x5f979e)
13/01/2016 03:03:01/usr/local/go/src/runtime/asm_amd64.s:1696 (0x4ea691)
13/01/2016 03:03:01
```

**Comment by bradrydzewski** [comment] 2016-01-13 03:13
Drone does not currently support tag events for gogs. If you look at this code we only support `push` hook events from Gogs based on the value of the `X-Gogs-Event` header:
https://github.com/drone/drone/blob/master/remote/gogs/gogs.go#L229

This would lead me to believe that Gogs sends a hook for tags with `X-Gogs-Event=push`. Is this the expected behavior? Or should Gogs send a separate hook for tags?

**Comment by cusspvz** [comment] 2016-01-13 03:22
> This would lead me to believe that Gogs sends a hook for tags with `X-Gogs-Event=push`. Is this the expected behavior? Or should Gogs send a separate hook for tags?

Actually i don't think so. Seems that Gogs [only has 2 hooks event types](https://github.com/gogits/gogs/blob/89244b74c61495c50ae071c203a2a2a0d078aa00/models/webhook.go#L262-L267), that leads me to suppose they trigger `create` when a new `ref` comes up and push whenever a commit comes up into the repo.

So maybe the answer to your second question is no, they are being sent as a `push` event but they add the `ref_type` property as `tag`.

**Comment by bradrydzewski** [comment] 2016-01-13 03:25
thanks for clarifying! could you get a sample payload from the hook history (in the gogs repository setting) and paste into this issue? That should help me issue a patch. Cheers!

**Comment by cusspvz** [comment] 2016-01-13 03:27
@bradrydzewski payloads I've posted are already from there :)

Before posting this issue I've been trying to figure out what was going on under the hood (I had also read lots of `drone` 's source code to understand how you manage to pickup conditional buildsteps), just forgot to see the logs. hahahah

**Comment by cusspvz** [comment] 2016-01-13 03:33
PS: Headers are equal on both cases, think you won't need them but, here they are:

```
Request URL: https://drone.example.com/hook?access_token=[hidden]
Request method: POST
Content-Type: application/json
X-Gogs-Delivery: 5c892a84-a774-4bd6-aac5-3606c01c6480
X-Gogs-Event: push
```

**Comment by gabrielpconceicao** [comment] 2016-01-14 18:16
@cusspvz @bradrydzewski just to add a note, same is happening not only with tags but with other branches rather than master as well.

Error stack is the same or similar.

**Comment by ClanStyles** [comment] 2016-01-16 02:06
This is now happening for me too... fresh install on Drone

**Comment by bradrydzewski** [comment] 2016-01-20 19:47
This is definitely a bug. The initial implementation assumed that, like GitHub, Gogs had different hook events for push vs tag vs branch which was obviously an incorrect assumption. The panic doesn't seem to hurt anything, other than dumping a stacktrace to the logs, so this isn't at the top of my todo list, but I'm happy to accept pull requests if someone wants this resolved sooner.

**Comment by ClanStyles** [comment] 2016-01-20 20:09
For me it fails to try to build thus making drone useless

**Comment by bradrydzewski** [comment] 2016-01-20 21:01
Please avoid calling things __useless__. We try to keep things positive and constructive in these threads. 

The Gogs implementation does not yet support pull requests or tag events, just push events. I can confirm push events work fine. Pull requests and tags should be ignored, but are currently resulting in a panic.

I am happy to accept a pull request that ignores non-push events to avoid the panic. I am also happy to accept a follow-up pull request that is capable of building tags and pull request events.

**Comment by cusspvz** [comment] 2016-01-25 17:08
> For me it fails to try to build thus making drone useless

@ClanStyles those kind of behaviors are not part/accepted of/on the Open-Source culture.

> I am happy to accept a pull request that ignores non-push events to avoid the panic. I am also happy to accept a follow-up pull request that is capable of building tags and pull request events.

@bradrydzewski I would like to have some impact here on drone, but unfortunately my Go skills are lower than basic stuff. The only contribution I wrote in Go, that I can recall, was on [flannel](https://github.com/coreos/flannel) and it was basic as hell. x)

I could give a try, but it would require some effort from you on helping me to understand not only how drone works under the hood, but how I would fix it as well. :disappointed: 

How complex you think this can go? (for a go novice)

**Comment by mathicalee** [comment] 2016-01-27 03:25
I had the same issue, but I saw a different payload sent to drone. I had 2 webhooks in gogs, so I removed the other one and the payload seems to be ok. No more 500 error :) (But a 404 error)

**Comment by bsauvajon** [comment] 2016-01-29 09:03
Hi,
interesting thread, I've been trying to trigger a build on a tag event with gogs and drone for 2 days, now I know why it doesn't work ! :yum:
My skills with go are too poor to make a pull request now, but if I've correctly undestood the code logic, the idea would be to :
 * Add the ref_type property to the Push_hook structure
 * Use this property in the buildFromPush function to change the Event property of the Build model

Is there a free go developper in the assistance ? :stuck_out_tongue:

**Comment by bradrydzewski** [comment] 2016-10-24 23:25
just merged fix into master. thanks @bsauvajon !

**Closed by bradrydzewski** 2016-10-24 23:25 UTC
Labels: bug, help wanted, remote/gogs

**Comment by mkny** [comment] 2019-09-19 22:22
Does anyone know if this issue is solved? 
Anytime that I try to generate a new tag, from Gogs it ignores.

For me it still returning this kind of message:
`{"level":"debug","msg":"webhook ignored","time":"2019-09-19T22:08:45Z"}
{"fields.time":"2019-09-19T22:08:45Z","latency":80610,"level":"debug","method":"POST","msg":"","remote":"XXX.XXX.XX.4:52230","request":"/hook","request-id":"XXXXXXXX","time":"2019-09-19T22:08:45Z"}`

Can anyone help?

**Comment by atomi** [comment] 2019-09-19 22:48
I recommend moving to Gitea.
