### ISSUE TITLE
Drone Cannot  be installed on a path of a domain name.

### ISSUE THREAD

**Issue by XuryaX** [drone/drone#2225] opened 2017-09-17 21:02 UTC
Drone can only be installed on a root path of a domain name.
Like
`http://abc.xyz.com` , 
But if we try to install it in a path of the domain name, it would still try to find it's resources in root (static,feed,api)
like if we install drone on
`http://abc.xyz.com/drone` , it would try to read resources like
`http://abc.xyz.com/static/app.css`
instead of
`http://abc.xyz.com/drone/static/app.css`

**Comment by bradrydzewski** [comment] 2017-09-17 22:32
duplicate of https://github.com/drone/drone/issues/475

**Closed by bradrydzewski** 2017-09-17 22:32 UTC
