### ISSUE TITLE
the last version drone web hook not work with gogs

### ISSUE THREAD

**Issue by damagedcode** [drone/drone#1890] opened 2016-12-23 04:22 UTC
drone version  
```
commit 342530772f4df9f9fb5ace9321e619c58e5b0f53
Merge: b83a719 b05c5f8
```

error log  
```
ERRO[0103] failure to get build config for RPM_Builder/Youzu_RPMs. invalid character '<' looking for beginning of value 
ERRO[0103] Error #01: invalid character '<' looking for beginning of value
```

**Comment by bradrydzewski** [comment] 2016-12-23 04:42
I am running latest Gogs `0.9.110.1222` and cannot confirm any issues with hooks. The error message you posted indicates that Drone is unable to parse your Yaml file due to an invalid character. This indicates either your Yaml is invalid or the API call to fetch the Yaml is not returning the file, and is instead returning a webpage.

I do not believe either of these are a Drone bug and am closing the issue. Instead I recommend looking at your Gogs logs.

I recommend we move this discussion to [discourse.drone.io](http://discourse.drone.io) and reserve the issue tracker for confirmed bugs and feature requests. Thanks!

**Closed by bradrydzewski** 2016-12-23 04:42 UTC

**Comment by damagedcode** [comment] 2016-12-23 05:42
but in same environment，drone 0.4.1+418 work will
