### ISSUE TITLE
Build status stuck on running if agent restarted during build

### ISSUE THREAD

**Issue by omerxx** [drone/drone#2189] opened 2017-09-04 18:54 UTC
Drone:   0.8.0-rc.3
DB:         Postgres (RDS on AWS)

My drone server went down during a running build.
Once it was brought back up I got a job running forever:
![image](https://user-images.githubusercontent.com/12237955/30036362-539003ba-91bb-11e7-8caf-8baf5585d77c.png)

I assume there should be a hardcoded timeout.
I would probably have to remove it physically from the DB to delete it.

**Comment by bradrydzewski** [comment] 2017-09-04 18:59
are you sure you didn't restart the agent too? Because Drone uses grpc, and when the server restarts, the agent reconects automatically (a feature of grpc) and resumes the updates

**Comment by omerxx** [comment] 2017-09-04 19:01
@bradrydzewski Both were terminated and restarted (new instances of them).
I have it deployed on ECS so that both of them are part of the same task.

**Comment by bradrydzewski** [comment] 2017-09-04 19:14
I've updated the title, since restarting the server is safe. Force restarting or upgrading the agent while a build is running is not yet supported. This is not a bug per-se, but is instead a limitation of the current implementation.

The safest way to restart your agent is with SIGINT.  This will gracefully stop the agent and allow running builds to complete before terminating.

The ability to lose agents and automatically recover is planned, but it is not something that will be implemented for 0.8 stable.

**Comment by omerxx** [comment] 2017-09-04 19:28
Can there be a hard-cancel feature or a hard-limit for running time?

**Comment by bradrydzewski** [comment] 2017-09-04 19:29
there is a `drone build kill <repo> <build>` command that you can use. You need to build the CLI from source, though, since it was recently added and not yet included in any releases.

**Comment by MOZGIII** [comment] 2017-09-21 21:07
You should add `stop_signal: SIGINT` to `docker-compose` examples.

**Comment by saward** [comment] 2018-03-20 04:01
This occasionally pops up for me.  Would be very useful if one could kill via GUI.  The 'cancel' action (via GUI) does not seem to do it.

**Comment by kubaj** [comment] 2018-04-18 09:03
Some recovery from failure of the agents would be nice. I was experimenting with Drone on the preemptible instances on the GKE and sometimes build stucks because an agent is killed.

**Comment by tboerger** [comment] 2018-04-18 13:11
The cli got a build kill command, but beside that 0.9 will include some recovery.

**Comment by chrisduong** [comment] 2018-07-10 08:54
@bradrydzewski could you share how would we restart the Agent Kubernetes Pod with SIGINT. I tried to execute “kill command” sending SIGINT but the Drone container does not come with kill command to do so.

**Comment by bradrydzewski** [comment] 2019-02-11 03:20
closing this as solved with agentless nomad and kubernetes options in 1.0

**Closed by bradrydzewski** 2019-02-11 03:20 UTC
