### ISSUE TITLE
Gitter 404

### ISSUE THREAD

**Issue by yellowmegaman** [drone/drone#2233] opened 2017-09-28 06:38 UTC
Hi there! After a  pause, i was looking for an advice about drone, and tried to find it on gitter, but channel is no longer available. 

Why?(

https://gitter.im/drone/drone

**Comment by bradrydzewski** [comment] 2017-09-28 07:00
duplicate of https://github.com/drone/drone/issues/2191. Community support moved to [discourse.drone.io](https://discourse.drone.io) with paid support available via Slack.

**Closed by bradrydzewski** 2017-09-28 07:00 UTC
