### ISSUE TITLE
Unable to access web UI

### ISSUE THREAD

**Issue by XPLOT1ON** [drone/drone#2089] opened 2017-06-26 06:10 UTC
I am unable to access the Drone Web UI after the set up. It would not response and eventually timeout. I have tried to `curl  127.0.0.1:10010` from my server console but, getting connection timeout
`docker ps` shows that, both drone server and drone agent started up and there were no error in the both services. the status of drone agent even shows that  `pipeline: request next execution`.

```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                        NAMES
afe78e042c14        drone/drone:0.7     "/drone agent"      30 minutes ago      Up 30 minutes       80/tcp, 443/tcp, 8000/tcp                    droneci_drone-agent_1
16865ecff0bf        drone/drone:0.7     "/drone server"     30 minutes ago      Up 30 minutes       80/tcp, 443/tcp, 127.0.0.1:10010->8000/tcp   droneci_drone-server_1

```
This is the docker-compose.yml

```
version: '3'

services:
  drone-server:
    image: drone/drone:0.7
    ports:
      - 127.0.0.1:10010:8000
    volumes:
      - /var/lib/drone:/var/lib/drone
    restart: always
    env_file:
      - /etc/drone-ci/server.env

  drone-agent:
    image: drone/drone:0.7
    command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file:
      - /etc/drone-ci/agent.env
```
Server.env
```
# Service settings
DRONE_SECRET=<SECRET>
DRONE_HOST=https://drone.example.com

# Registration settings
DRONE_OPEN=true
DRONE_ADMIN=<BitBucket USERNAME>
DRONE_ORGS=<BitBucket TEAM>

# VCS Settings
DRONE_BITBUCKET=true
DRONE_BITBUCKET_CLIENT=<BitBucket-CLIENT>
DRONE_BITBUCKET_SECRET=<BitBucket-SECRET>
```

agent.env
```
DRONE_SECRET=<SECRET>
DRONE_SERVER=ws://drone-server:8000/ws/broker
```

**Comment by tboerger** [comment] 2017-06-26 06:17
You are binding the server to localhost, so in that case you can't access it from remote

**Comment by XPLOT1ON** [comment] 2017-06-26 06:32
@tboerger I used nginx to reverse my domain to localhost. Also i am unable to access it on the actual server its self too (tried curl 127.0.0.1:10010 on server).

**Comment by bradrydzewski** [comment] 2017-06-26 11:57
Duplicate of https://stackoverflow.com/questions/44747054/drone-ci-web-not-responding

**Closed by bradrydzewski** 2017-06-26 11:57 UTC
