### ISSUE TITLE
CPU load on the client is significant

### ISSUE THREAD

**Issue by drahnr** [drone/drone#1236] opened 2015-10-15 07:18 UTC
When I run a build and watch the build process from firefox, it tends to consume one CPU core (one total CPU core, i7 3rd gen, 4700 or so). I think that is quite significant.

I am using the latest rpm being provided as of today.

**Comment by bradrydzewski** [comment] 2015-10-15 15:01
duplicate of #733 (issue shouldn't be specific to chrome)

**Closed by bradrydzewski** 2015-10-15 15:01 UTC
