### ISSUE TITLE
Use Bitbucket and Github at the same time

### ISSUE THREAD

**Issue by Mojo90** [drone/drone#2141] opened 2017-07-25 16:27 UTC
In my server.env I have the following:

```
# Service Settings
DRONE_SECRET=XXX
DRONE_HOST=XXX

# Registration settings
DRONE_OPEN=false
DRONE_ADMIN=XXX

# GitHub Settings
DRONE_GITHUB=true
DRONE_GITHUB_CLIENT=XXX
DRONE_GITHUB_SECRET=XXX

# Bitbucket Settings
DRONE_BITBUCKET=true
DRONE_BITBUCKET_CLIENT=XXX
DRONE_BITBUCKET_SECRET=XXX
```

Now if I go to the Dashboard and login it automatically uses Github. If I comment out Github it uses Bitbucket. So my question is propably integrate both services at the same time with one instance does not work, is that correct or did I miss a configuration?

**Comment by bradrydzewski** [comment] 2017-07-25 16:28
duplicate of https://github.com/drone/drone/issues/1503

**Closed by bradrydzewski** 2017-07-25 16:28 UTC
