### ISSUE TITLE
Documentation: How to know which agent runs which build

### ISSUE THREAD

**Issue by adrienverge** [drone/drone#2117] opened 2017-07-18 07:20 UTC
Hi,

We use Drone on multiple machines with different hardware capabilities. I'd like to know which builds runs on which agent, for debugging purpose. Unfortunately I couldn't find anything in the docs, in GitHub issues or on [stackoverflow/drone.io](stackoverflow.com/questions/tagged/drone.io).

1. Is there a way to print the agent's name? There does not seem to be an env variable for that. Otherwise is there a way to define custom per-agent variables, like asked in drone/drone#1808? If not, is there a way to get this information by ssh-ing on the Drone server (or agents) after builds are complete and containers deleted?

2. I'd like to improve Drone documentation by answering this question, because I think it's a legitimate one :)

**Comment by jmccann** [comment] 2017-07-18 11:53
I don't think this is a matter of documentation but rather it is just not possible ATM.

Seems to be related to #1496.

**Comment by bradrydzewski** [comment] 2017-07-18 13:38
closing as duplicate of #1496

**Closed by bradrydzewski** 2017-07-18 13:38 UTC
