### ISSUE TITLE
[Proposal] support custom volume to mapping source-code when use k8s mode

### ISSUE THREAD

**Issue by wangwenpei** [drone/drone#2857] opened 2019-10-10 02:22 UTC
Dear all,

Drone is an awesome CI/CD tool and we use it about 3 years. thanks again !
recently, we upgrade our workflow to work with Drone k8s build feature.

but we found it's a little slow because when use k8s mode, drone-runner-pod always create a new volume mapping because pod and namespace name is random value.it's make sense. we should physical isolation different pod.

but I think maybe we can set a volume to mapping source-code & only for source-code. all pod work on same k8s node will share same path. this can save a lot of time.

**Comment by bradrydzewski** [comment] 2019-10-10 02:28
dupe of https://github.com/drone/drone-runtime/issues/82

**Closed by bradrydzewski** 2019-10-10 02:28 UTC
