### ISSUE TITLE
URL Prefix

### ISSUE THREAD

**Issue by DaAwesomeP** [drone/drone#1456] opened 2016-02-02 18:32 UTC
I have set up my CI server behind an Nginx reverse proxy that maps it to `/drone/`. However, is there a way to let Drone know of this prefix? It redirects to `/login` instead of `/drone/login`.

**Comment by bradrydzewski** [comment] 2016-02-02 19:02
duplicate of https://github.com/drone/drone/issues/475

**Closed by bradrydzewski** 2016-02-02 19:02 UTC
