### ISSUE TITLE
path error,repository cannot sync

### ISSUE THREAD

**Issue by lxd5866** [drone/drone#2773] opened 2019-08-04 06:44 UTC
repository path GroupA/GroupB/projectName is recognized as GroupB/projectName， find error.
gitlab:11.1.4 
drone:1.0

**Comment by bradrydzewski** [comment] 2019-08-04 06:46
closing as duplicate of https://github.com/drone/drone/issues/2009

**Closed by bradrydzewski** 2019-08-04 06:46 UTC
