### ISSUE TITLE
build artifacts

### ISSUE THREAD

**Issue by hd-deman** [drone/drone#966] opened 2015-04-09 15:34 UTC
No way to get build artifacts (screenshots/logs/etc) created during test suite. Nice example of build-artifacts implementation https://circleci.com/docs/build-artifacts.

**Comment by daMupfel** [comment] 2015-04-09 17:09
I like this approach :+1:

**Comment by thomasf** [comment] 2015-04-09 17:48
I think that should be a job for a publish job to put those in a content repository of choice.. I like how drone currently does not handle artifacts, keeps things cleanly separated.  (At least this seems to be true for the version I am running.)

**Comment by thomasf** [comment] 2015-04-09 17:52
The hosted drone.io seems to have this http://docs.drone.io/artifacts.html .. Maybe it works by publishing using some internal publishing function.

**Comment by thomasf** [comment] 2015-04-09 18:05
Also you should have searched the issue system first:
  https://github.com/drone/drone/search?q=artifacts&type=Issues&utf8=%E2%9C%93
Specifically this is more or less a duplicate of #306  except that issue does not currently describe anything about a user interface.

**Comment by bradrydzewski** [comment] 2015-04-09 18:15
Thanks for the link, let's track in #306 to avoid duplicate issues. For an immediate solution, I recommend using the S3 plugin (or others) to archive files. It isn't perfect, but should work.

We will probably do something similar to what is described here:
https://github.com/drone/drone/issues/239#issuecomment-80758786

It isn't really practical for Drone to build everything (code coverage, commiter analytics, code quality, dependency analysis, artifacts, etc) directly into the codebase. Yet people want all of these things inside Drone **and more**. How do we pick winners? And should we? Drone can't do Coverage better than coveralls or artifact management better than Bintray, for example, and if we try we will probably fail. It will distract us from focusing on great CI.

I think a better strategy is to find a way to integrate 3rd party systems with Drone as described in https://github.com/drone/drone/issues/239#issuecomment-80758786.  The *tl;dr* is that we will expose something similar to the GitHub Status API but for Drone. You will be able to tag builds with useful information, and links to external resources.

We could, for example, create an artifact service (a separate server) that tightly integrates with Drone using the API and the Status API. It could **look and feel** like Drone. It could even have Drone's branding. It just might be a different url, and you would link to it from your build. I think we could make the UX seamless, however.

This approach allows for unlimited integrations, and can meet the needs of every Drone user no matter how obscure their needs may be.

I would love to engage everyone in designing the Drone status API to support all of these different use cases. Open issue here: https://github.com/drone/drone/issues/927

**Closed by bradrydzewski** 2015-04-09 18:15 UTC

**Comment by kinosang** [comment] 2019-09-09 07:00
any update?

**Comment by gp-Airee** [comment] 2020-03-27 13:48
Really would love this.

**Comment by dwilhel1** [comment] 2020-04-17 17:39
My team would also like to see this as a feature added to Drone!
