### ISSUE TITLE
RFC: Store and display individual pipeline steps

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#1857] opened 2016-11-16 21:56 UTC
Currently in the Drone UI there is no information on what the pipeline looks like and why a certain step was not run within a build. This makes debugging difficult especially for users who are new to Drone.

I would like to propose that the logs contain metadata on the build itself and what is happening within it so users can diagnose their YAML files for any issues with configuration.

During the preparation for the build the agent should output metadata on what the pipeline looks like and why a certain step is not going to run. It could also potentially let the user know what secrets are present and if the image matches why it is not injected into the current build.

Within the UI you could do something like this. This would visualize the pipeline and show why certain steps are executing but others are not. Programmer art follows.

![pipeline_proposal](https://cloud.githubusercontent.com/assets/666297/20367423/3e1944a8-ac04-11e6-8682-41dabe5f8d23.png)

**Comment by bradrydzewski** [comment] 2016-11-17 01:26
so we should be able to trace why a step is skipped and write that reason to the build logs as you can see below:

```diff
-	if !pipeline.Head().Constraints.Match(
-		a.Platform,
-		payload.Build.Deploy,
-		payload.Build.Event,
-		payload.Build.Branch,
-		status, payload.Job.Environment) { // TODO: fix this whole section
-
-		pipeline.Skip()
-	} else {
-		pipeline.Exec()
-	}

+	var (
+		skip = true
+		reason string
+	)
+
+	switch {
+	case !c.Environment.Match(target):
+		reason = "..."
+	case !c.Event.Match(event):
+		reason = "..."
+	case !c.Branch.Match(branch):
+		reason = "..."
+	case !c.Status.Match(status):
+		reason = "..."
+	case !c.Matrix.Match(matrix):
+		reason = "..."
+	default:
+		skip = false
+	}
+	
+	if skip {
+		pipeline.Skip()
+	} else {
+		pipeline.Exec()
+	}
```

this would happen here:
https://github.com/drone/drone/blob/master/agent/agent.go#L220

the skip reason could be logged as meta-data using the existing logging type and metadata enumeration, which you can see here:
https://github.com/drone/drone/blob/master/build/types.go#L9

**Comment by bradrydzewski** [comment] 2016-11-21 16:35
I like the sequence-diagram style pipeline visualization

<img width="500" alt="screen shot 2016-11-21 at 5 34 28 pm" src="https://cloud.githubusercontent.com/assets/817538/20491174/d5324424-b010-11e6-9dba-9c429cd4e2d6.png">

**Comment by Spedge** [comment] 2017-03-10 08:49
Any movement on this @bradrydzewski ? Quite an exciting concept - especially if you could re-start parts of the pipeline?

**Comment by bradrydzewski** [comment] 2017-03-13 03:37
@Spedge agreed this will be a nice feature. I am not actively working on new features right now. I'm focused on stabilizing the codebase and getting things documented before I jump into the next feature sprint.

The challenge with this change is that it ends up being somewhat complex. We do not currently store the steps in the database as structured data. The steps are instead parsed from the logs. Each log entry is tagged with metadata including the timestamp, line number and process name (ie step). This data is aggregated in the UI to organize the logs by process name.

Ideally we would store the steps as structured data. This also probably means storing the logs for each step as separate entries, instead of a single blob for the entire build. This would allow us to tag each step with useful metadata such as total duration, exit code, resource usage, whether or not it was skipped, and more and could lead to some nice visualizations in the UI. This sort of structural change ends up impacting almost every tier of the code (front-end, websockets, api, database, log server, agent to server protocol).

So while this definitely won't be an easy feature to implement, it will certainly bring some exciting new capabilities. I think the best way to push this forward would be to come up with some different database designs so we can understand pros / cons and performance and database size implications. I'm definitely open to help in this area. Once we know how we are going to structure the data we can figure out how to start updating the surrounding modules accordingly, hopefully one at a time :)

**Comment by bradrydzewski** [comment] 2017-03-15 02:50
My proposal would be to alter the data structure to support a more tree-like structure. This would involve removing the `jobs` table and replacing with something more generic that could represent matrix jobs, but also their sub-processes.

```sql
CREATE TABLE procs (
 proc_id         INTEGER PRIMARY KEY AUTOINCREMENT
,proc_build_id   INTEGER
,proc_pid        INTEGER
,proc_ppid       INTEGER
,proc_pgrp       INTEGER
,proc_name       TEXT
,proc_state      TEXT
,proc_error      TEXT
,proc_exit_err   BOOLEAN
,proc_exit_code  INTEGER
,proc_created    INTEGER
,proc_updated    INTEGER
,proc_started    INTEGER
,proc_finished   INTEGER
,proc_tty        TEXT
,proc_platform   TEXT
,proc_environ    TEXT
,proc_machine    TEXT
);
```

We would then need to store the build logs for each process:

```sql
CREATE TABLE files (
 file_id        INTEGER PRIMARY KEY AUTOINCREMENT
,file_build_id  INTEGER
,file_proc_id   INTEGER
,file_name      TEXT
,file_mime      TEXT
,file_data      BLOB
,file_created   INTEGER
,file_updated   INTEGER
);
```

Unfortunately progress and new features of this nature come with the guarantee that we are going to break things. So that is my only warning to the community. If we push forward with this sort of feature we are going to create (more) breaking changes, and I'm not personally going to spend my cycles coming up with automated data transformation / migration scripts (unless someone wants to fund it). Otherwise it would need to be a community effort.

**Comment by bradrydzewski** [comment] 2017-03-25 16:14
Update. I'm now working on this. I created a github project to track all breaking changes that I wanted to complete prior to 1.0 and this is one of the last (and biggest) items on the list
https://github.com/drone/drone/projects/1

I expect an initial implementation in ~2 weeks, given the complexity involved. Please note that the initial implementation will focus on the server side, agent to server, and database changes required. It will not include any UI visualizations. That is phase 2

**Comment by bradrydzewski** [comment] 2017-04-03 09:52
ok ... if someone wants to really see this advanced and wants to help, I could really use a react component that takes the below javascript object and create a well-styled graph (similar to Jenkins image above)

```json
[
        {
          "pid": 2,
          "ppid": 1,
          "pgid": 2,
          "name": "clone",
          "state": "success",
          "exit_code": 0,
          "start_time": 1491208667,
          "end_time": 1491208672
        },
        {
          "pid": 3,
          "ppid": 1,
          "pgid": 3,
          "name": "frontend",
          "state": "success",
          "exit_code": 0,
          "start_time": 1491208672,
          "end_time": 1491208704
        },
        {
          "pid": 4,
          "ppid": 1,
          "pgid": 3,
          "name": "backend",
          "state": "success",
          "exit_code": 0,
          "start_time": 1491208672,
          "end_time": 1491208704
        },
        {
          "pid": 5,
          "ppid": 1,
          "pgid": 5,
          "name": "deploy",
          "state": "success",
          "exit_code": 0,
          "start_time": 1491208672,
          "end_time": 1491208704
        }
]
```

The above javascript object would look like this in graphical form:

![diagram](https://yuml.me/diagram/plain/activity/(start)-%3E(clone)-%3E%7Ca%7C,%7Ca%7C-%3E(frontend)-%3E%7Cb%7C,%7Ca%7C-%3E(backend)-%3E%7Cb%7C,%7Cb%7C-%3E(deploy)-%3E(end).png)

Note that parallel steps are denoted by the `pgid` field. Steps with the same group are executed in parallel.

Any takers?

**Comment by bradrydzewski** [comment] 2017-04-05 09:36
ok, the pull request to store individual steps as structured data is complete. This was a major breaking change and there are going to be a lot of rough edges and even some regressions. I wouldn't rule out more breaking changes and would not advise `drone:0.6` until we announce a release candidate.

... but at least the hard part is done 😄

**Comment by onbjerg** [comment] 2017-04-23 03:42
@bradrydzewski Is the React component still needed? It seems like Jenkins has their pipeline graph in a seperate repository [here](https://github.com/jenkinsci/jenkins-design-language/blob/master/src/js/components/PipelineGraph.jsx) and that they are constructing an SVG from some data in the Blue Ocean repository.

I'm fairly good at React, so I might want to take a stab at this if it's not done already.

**Comment by bradrydzewski** [comment] 2017-07-19 17:18
The drone server and agent changes are in place and we now display all steps in the user interface at the start of the build. We have also added a `skipped` status.

I am therefore moving this issue to the drone-ui repository, since the remaining action items are all front-end work. Moved to https://github.com/drone/drone-ui/issues/130

**Closed by bradrydzewski** 2017-07-19 17:18 UTC
