### ISSUE TITLE
White Page with logging in via Github oauth

### ISSUE THREAD

**Issue by bscott** [drone/drone#1041] opened 2015-06-04 00:46 UTC
After setting up Github oauth, I'm redirected to a white page when Github redirects my login to the Drone Callback URL. 

Any one having this same issue?

**Comment by bradrydzewski** [comment] 2015-06-04 00:50
duplicate of #660 to display error messages in the UI

check out `/var/log/upstart/drone.log` for full details of why it is failing, or `docker logs` if running Drone in docker. Login failures as you've described are typically a result of incorrect configuration.

feel free to use our chat room (gitter.im/drone/drone) if you have questions or need help troubleshooting further

**Closed by bradrydzewski** 2015-06-04 00:50 UTC
