### ISSUE TITLE
Registry cannot be removed if it has https:// in its name

### ISSUE THREAD

**Issue by arno01** [drone/drone#2341] opened 2018-02-11 20:44 UTC
It appears that one cannot remove the registry from a repository if registry contains ``https://`` in its name.

https://discourse.drone.io/t/unable-to-delete-registry-from-repository/943

**Comment by bradrydzewski** [comment] 2018-02-11 21:07
duplicate of https://github.com/drone/drone/issues/2334

**Closed by bradrydzewski** 2018-02-11 21:07 UTC
