### ISSUE TITLE
I can't activate Drone in my "owner" repository of Gitlab

### ISSUE THREAD

**Issue by gingi99** [drone/drone#1043] opened 2015-06-05 05:02 UTC
I posted .drone.yml to my owner repository in Gitlab.
After that, I pushed the button written "Acivate Now" in Drone.
However, it doesn't work well.

JavaScript says "500 Internal Server Error".

However, in this case of my master repository in Gitlab, when I pushed the button, it works well.

**Comment by bradrydzewski** [comment] 2015-06-05 05:09
do you have administrative access to this repository in GitLab? administrative access is required in order to add a post-commit hook (and possibly ssh key) to the repository.

**Comment by rmwpl** [comment] 2015-06-10 07:00
Having same issue here.
Activation doesn't work for GitLab 7.11.4 even for a user with administrative access.
No key or webhook is added the the repo configuration.
I've also tried some webhook entered by hand, but with no success (I've added drone's key to deploy keys).

**Comment by Bugagazavr** [comment] 2015-06-10 08:48
Repo name contains 'dot' char?

**Comment by rmwpl** [comment] 2015-06-10 09:16
Nope. Only lowercase letters.

**Comment by Bugagazavr** [comment] 2015-06-10 09:54
This is strange because now, im add a repo and activate this, and all is fine.

Can you provide drone and gitlab log, when you try to activate repository?

**Comment by rmwpl** [comment] 2015-06-11 10:06
Unfortunately I can't see any related drone logs (actually, drone doesn't log anything but the sync process).
There are also no related GitLab logs.
What is interesting however are the webserver logs:
```192.168.3.41 - - [10/Jun/2015:13:34:42 +0800] "POST https://GITLAB_HOST/api/v3/projects/dockerfile%2Fdns-cache/hooks HTTP/1.1" 302 105 "-" "Go 1.1 package http" 
127.0.0.1 - - [10/Jun/2015:13:34:42 +0800] "POST //api/v3/internal/allowed HTTP/1.1" 200 28 "-" "Ruby"
192.168.3.41 - - [10/Jun/2015:13:34:43 +0800] "GET /users/sign_in HTTP/1.1" 200 4281 "https://GITLAB_HOST/api/v3/projects/dockerfile%2Fdns-cache/hooks" "Go 1.1 package http"```

There is a lot of pairs (POST to `hooks` and GET to `sign_in`) like this in the time frame of drone tests.

So it seems to me that whenever drone want's to do a POST to create a hook it is being redirected to sign-in page. There is no error shown in the drone WebGUI, in fact it claims it succeeded to activate the project.

**Comment by Bugagazavr** [comment] 2015-06-11 10:08
@rmwpl if you use ubuntu, you can see logs at `/var/log/upstart/drone.log`

**Comment by rmwpl** [comment] 2015-06-11 10:12
As I mentioned before, I'm using the drone's official docker image. Is there any way to manually specify the logfile location?

**Comment by Bugagazavr** [comment] 2015-06-11 10:14
@rmwpl you using manually gitlab setup or omnibus?

```sh
docker logs CONTAINER
```

**Comment by rmwpl** [comment] 2015-06-11 10:18
Didn't detach the container, no logs were showing up apart from sync logs.
GitLab was set up manually.

**Comment by Bugagazavr** [comment] 2015-06-11 10:22
@rmwpl so, we can't reproduce all possible configurations of gitlab, officially we support only omnibus package and gitlab.com. Maybe problem in your nginx/apache configuration. You can try to send API requests manually.

**Comment by rmwpl** [comment] 2015-06-11 10:25
Just took a look at GitLab's manual, it states that hook creation request should be POSTed to '/projects/:id/hooks'.
The log fragment I provided above clearly shows that drone is POSTing the request to '/api/v3/projects/...'.

I can try and create the hook by hand. Can you please show an example of a hook URL I should put in the project?

**Comment by Bugagazavr** [comment] 2015-06-11 10:30
u thin we not need reproduce drone hook url, just try to execute
```sh
curl +XPOST https://GITLAB_HOST/api/v3/projects/dockerfile%2Fdns-cache/hooks?push_events=true&merge_requests_events=true&tag_push_events=true&url=http://example.com&private_token=[TOKEN]
```

**Comment by rmwpl** [comment] 2015-06-15 08:31
Well, can't really execute that, since drone didn't create a private token. Actually, drone didn't create sqlite db at all, so there's no place to get the token from.
*Please*, can you provide a sample hook URL that I can enter manually into gitlab project configuration?

**Comment by bradrydzewski** [comment] 2015-06-15 15:19
@rmwpl http://my.drone.com/api/hook/gitlab.com/{TOKEN}

Drone creates a secret token that it appends to your post commit hook. This token is stored in the database, and matched to the incoming web-hook to verify its identity. Drone saves this token in the database **after** the post-commit hook is successfully created. If Drone fails to create the post-commit hook, no token is saved to the database.

Without a token, there is no URL for you to manually enter into GitLab

@Bugagazavr seems willing to help you troubleshoot and has asked to manually curl the server. I presume the response will help him diagnose further and suggest next steps. He wrote the GitLab code and is most qualified to help you get things working.

**Comment by rmwpl** [comment] 2015-06-16 01:58
So I tried CURLing with a dummy token, here's the result:

```$ curl -XPOST 'https://GITLAB_HOST/api/v3/projects/dockerfile%2Fdns-cache/hooks?push_events=true&merge_requests_events=true&tag_push_events=true&url=http://192.168.5.33&private_token=DUMMY_TOKEN'
<html><body>You are being <a href="https://GITLAB_HOST/users/sign_in">redirected</a>.</body></html>```

So it's pretty much the same as in the webserver's logfile - maybe Drone would be able to create a hook if it wasn't redirected by GitLab to the login page.

**Comment by rmwpl** [comment] 2015-06-16 02:49
So i did some more digging, found the drone.sqlite db file in the docker container and found tokens :)
After that, I created the hook myself, launched `tcpflow` and clicked on "test hook".
What happend was:
```
192.168.001.208.47220-192.168.005.033.00080: POST /api/hook/gitlab.com/8tBKV7HuXIVAPazc0JkNxKx8g8FmZ4Z3qMgTyqHB HTTP/1.1
Content-Type: application/json
X-Gitlab-Event: Push Hook
Connection: close
Host: 192.168.5.33
Content-Length: 1404


192.168.001.208.47220-192.168.005.033.00080: {"object_kind":"push","before":"8b23c84dcdfd641ff7845bd403bb863165c4cc6a","after":"33c2c6ad717858858952e59af172f016b1e58f07","ref":"refs/heads/master","checkout_sha":"33c2c6ad717858858952e59af172f016b1e58f07","message":null,"user_id":87,"user_name":"Robert.w","user_email":"robert.w@sam-media.com","project_id":246,"repository":{"name":"test","url":"git@GITLAB_HOST:robert.w/test.git","description":"","homepage":"https://GITLAB_HOST/robert.w/test","git_http_url":"https://GITLAB_HOST/robert.w/test.git","git_ssh_url":"git@GITLAB_HOST:robert.w/test.git","visibility_level":0},"commits":[{"id":"33c2c6ad717858858952e59af172f016b1e58f07","message":"drone test\n","timestamp":"2015-06-16T10:19:38+08:00","url":"https://GITLAB_HOST/robert.w/test/commit/33c2c6ad717858858952e59af172f016b1e58f07","author":{"name":"jx","email":"jx@darkstar"}},{"id":"aaa65862b72498ab8182a0bf782bd4c4c7cf51cd","message":"drone test\n","timestamp":"2015-06-10T17:10:58+08:00","url":"https://GITLAB_HOST/robert.w/test/commit/aaa65862b72498ab8182a0bf782bd4c4c7cf51cd","author":{"name":"jx","email":"jx@darkstar"}},{"id":"8b23c84dcdfd641ff7845bd403bb863165c4cc6a","message":"drone test\n","timestamp":"2015-06-10T17:09:29+08:00","url":"https://GITLAB_HOST/robert.w/test/commit/8b23c84dcdfd641ff7845bd403bb863165c4cc6a","author":{"name":"jx","email":"jx@darkstar"}}],"total_commits_count":3}
192.168.005.033.00080-192.168.001.208.47220: HTTP/1.1 404 Not Found
```

So as you can see drone responds with 404 to the request generated by the hook.

**Comment by Bugagazavr** [comment] 2015-06-16 03:44
@rmwpl It's looks like something wrong with configuration fronted server. For example your server can be configured to decode slashes `%2F` to `/`, this is wrong, because gitlab requires `%2F`.

try to open in browser
```
https://GITLAB_HOST/api/v3/projects/dockerfile%2Fdns-cache?private_token=[your_token]
```

if you get 401 or 404, try to use integer repository id instead string
```
https://GITLAB_HOST/api/v3/projects/[id]?private_token=[your_token]
```

**Comment by rmwpl** [comment] 2015-06-16 08:53
I tested and looks like passing numeric ID works. Unfortunately I can't use `NoDecode` for `AllowEncodedSlashes` configuration at the moment, so I tried again with creating the hook by hand.

As I mentioned before, Drone responds with 404 for requests to URL constructed from the template provided by @bradrydzewski; in some other issue I found, that Drone was using `/v3/` instead of `/api/`, so I tried it and it responds with some HTML, but still I can't see any commits...

**Comment by Bugagazavr** [comment] 2015-06-16 11:51
Anyway, when drone got a hook, drone need download `.drone.yml` from api, and drone uses `namespace%2Frepository`, no way to use drone with gitlab configuration `NoDecode`

**Comment by Bugagazavr** [comment] 2015-06-16 12:03
@bradrydzewski can we add in 0.4.0 repository column `project_alt_id`, to store number id and use it to call gitlab API methods?

**Comment by bradrydzewski** [comment] 2015-06-16 15:45
@Bugagazavr could we make an API call on-the-fly to retrieve the ID instead of storing in the database?

**Comment by Bugagazavr** [comment] 2015-06-16 16:00
@bradrydzewski it's possible but wee need to fetch list of all projects, and search needed project in array, not good solution.

**Comment by bradrydzewski** [comment] 2015-06-16 16:02
A few questions. Does this impact all GitLab installations? Does this impact newer version of GitLab or older?

**Comment by bradrydzewski** [comment] 2015-06-16 16:04
also, looks like this API call might work. It accepts an ID, but according to the docs and ID may be an integer `id` or project `namespace/project_name`. The response yields the project id:
https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md#get-single-project

would that work as an alternative?

**Comment by Bugagazavr** [comment] 2015-06-16 16:05
@bradrydzewski nope only for some installations, this problem on apache/nginx configuration, i think we not need support none official installations ( https://about.gitlab.com/downloads/ ) and cloud version gtilab.com. But use id instead, allow to avoid this issue.

**Comment by rmwpl** [comment] 2015-06-17 02:05
@Bugagazavr, thanks, that explains a lot! Will try today to set up new apache instance with proper configuration.

**Comment by rmwpl** [comment] 2015-06-17 05:55
Just tested with new apache installation and `AllowEncodedSlashed` set to `NoDecode`.
Still getting 404. **But** I noticed, that 404 is actually generated by GitLab.
It's okay, when I use project id instead of project name containing `%2F`.
So it seems like *GitLab 7.11.4 installed from source supports only numeric project identifiers*.

Gonna read about upgrading to Omnibus, but I think it would be better to use numeric identifiers in Drone as well.

**Comment by rmwpl** [comment] 2015-06-17 07:09
Got it working.
Turns out that `mod_proxy` was re-encoding the URL, so even though `AllowEncodedSlashes` was set to `NoDecode` the URL arriving at GitLab listening behind Apache-RP was containing `%252F` instead of `%2F`.
At first it seemd like the solution is to use `nocanon` directive with `ProxyPass` and `ProxyPassReverse`. It worked really well with cURL, but unfortunatelly didn't with Drone.

So, after some more googling I found it.
**The actual solution** is to use `RewriteRule` with `NE` flag in place of `ProxyPass`, but to leave `ProxyPassReverse` in place.

Now Drone is able to communicate with GitLab using alphanumeric project identifiers in encoded URLs; hooks are being created, Drone is launching builds.

Thank you @Bugagazavr and @bradrydzewski!

**Comment by letusfly85** [comment] 2015-07-01 11:41
Is there any relation to below?

https://github.com/drone/drone/pull/1076

And I found other hook not work, today.

**Comment by richarddowner** [comment] 2015-07-06 20:33
@rmwpl Could you show me your apache config regarding the RewriteRule? I am having the same problem but cant seem to set the RewriteRule properly... Thanks

**Comment by c1pherx** [comment] 2015-08-19 03:12
@richarddowner Add the following to your apache config. Obviously change the IP / port as necesary.

	RewriteEngine on
	RewriteRule "^(.*)" "http://127.0.0.1:10080/$1" [P,NE]
        ProxyRequests Off
        ProxyPreserveHost on
        ProxyPassReverse / http://127.0.0.1:10080/ nocanon

This got it working for me too.

@rmwpl Good catch!

**Comment by bradrydzewski** [comment] 2015-10-26 19:07
sounds like this is resolved with changes to apache config. closing

**Closed by bradrydzewski** 2015-10-26 19:07 UTC
