### ISSUE TITLE
Deprecated Docker Engine Feature

### ISSUE THREAD

**Issue by MorphBonehunter** [drone/drone#1946] opened 2017-02-18 22:59 UTC
Today i play a little bit with drone and see the following in my docker (v 1.13.1 on Archlinux) log:
```
DEPRECATED: Setting host configuration options when the container starts is deprecated and has been removed in Docker 1.12
```
So as this is also stated [in the Docker Docs](https://docs.docker.com/engine/deprecated/#hostconfig-at-api-container-start) maybe someone could check if this breaks something in drone (my testings are very basic and i can not find any failures at the moment).
The only other errors in the docker log are
```
Error closing logger: invalid argument
```
just after a lot of log messages generated during the pipeline run.
As i can not find any clues about this message (besides an closed issue #1817 and docker 1.12), maybe this is related.

**Comment by bradrydzewski** [comment] 2017-02-18 23:24
> So as this is also stated in the Docker Docs maybe someone could check if this breaks something in drone (my testings are very basic and i can not find any failures at the moment).

@MorphBonehunter per the [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md) the issue tracker is reserved for confirmed bugs. Since there is no known issue I am closing this. If we determine there is an actionable issue or bug we can re-open.

**Closed by bradrydzewski** 2017-02-18 23:24 UTC

**Comment by MorphBonehunter** [comment] 2017-02-19 14:03
@bradrydzewski  ok, i assume using a deprecated and removed feature is a bug but you are right, it causes no error at the moment.
Do you think i should start a new discourse thread for further discussion?
