### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by iammichiel** [drone/drone#2269] opened 2017-11-24 10:51 UTC
Hello, 

When upgrading from 0.5 to 0,8 version, we noticed a huge performance hit. Our builds went from a couple of minutes, to over 10 minutes. 

When running a simple step such as installing dependencies through yarn, the task itself is completed in a given time. However, the container seems to run for another amount of time before killing itself. 
A simple example : 
- a front-end building step, running tasks such as yarn, bower and gulp runs in 73 seconds. Which is quite consistent with our build times from the 0.5 version. However, the container on the left side of the UI shows a 01:49 ~ 109 seconds. (Quite obvious but all other steps are waiting for the front-end task to end before starting)
- a composer (php package deps) runs in 6 seconds, container runs for 9.
- unit tests run 7 minutes, container runs for 7 minutes 40.

Exactly, the same happens on all other tasks. 
Is there any way to debug ? Logging? System settings?

**Comment by bradrydzewski** [comment] 2017-11-24 17:13
We have not received any reports of performance issues with 0.8. Furthermore, Drone does not run your commands. Docker runs your commands, and Drone does not have any influence over how fast something like `yarn install` runs inside a Docker container.

Since there are no other reports of performance issues and not steps to reproduce, I am closing this issue. I recommend starting a discussion thread at [disourse.drone.io](https://discourse.drone.io), per our issue template, to discuss further.

If we discover this is a Drone issue we can re-open this issue to track.

**Closed by bradrydzewski** 2017-11-24 17:13 UTC
