### ISSUE TITLE
Docker run of drone:0.4 fails

### ISSUE THREAD

**Issue by stevenpall** [drone/drone#1279] opened 2015-10-29 16:30 UTC
I tried running a test instance of drone 0.4 today as per http://readme.drone.io/docs/setup/ and received the following error: 
```
docker run -it --rm -v /var/lib/docker.sock:/var/lib/docker.sock -p 8080:8000 --name drone drone/drone:0.4
INFO[0000] using database driver sqlite3
INFO[0000] using database config /var/lib/drone/drone.sqlite
ERRO[0000] unable to open database file
FATA[0000] migration failed
```
Note that I didn't specify `/var/lib/drone` as a volume so as to keep it separate from our existing installation. Does the sqlite database file need to be initialized in some way before running the drone container? Thanks!

**Comment by bradrydzewski** [comment] 2015-10-29 16:50
@stevenpall looks like it is failing because it wants `/var/lib/drone` to exist. Docker would usually auto-create this directory inside the container when mounting an external volume.

I'm a bit torn on this one because the fix is pretty simple. We can add a command to the Dockerfile to create the directory when we build the image:

```
RUN mkdir -p /var/lib/drone
```

The reason I'm torn is that when using SQLite one typically wants to mount a volume to the host machine to ensure the database persists outside the container to enable upgrades, etc (I understand you are just testing, so this isn't the case).  But this error could potentially prevent a mis-configuration that would result in database loss.

Need to think this one through a bit more. But for now you can mount the volume on the host machine to a temp directory to avoid impacting your existing Drone install. That would look something like this `-v /tmp/drone:/var/lib/drone`. Alternatively, you could run SQLite in-memory with `-e DATABASE_CONFIG=:memory:`

**Comment by stevenpall** [comment] 2015-10-29 18:27
Okay, that's probably a good "safety net" feature. I'm confused as to why the directory doesn't get created, though, as it's specified as a `VOLUME` in the Dockerfile. Anyway, perhaps, if `/var/lib/drone/drone.sqlite` doesn't exist, a hint could be given as to what the issue is ("unable to open database file - ensure that /var/lib/drone has been volume mounted" or something to that effect).

Also, this is tangentially-related: since I hadn't specified the `dronerc` env file, I got a second error
```
INFO[0000] using database driver sqlite3
INFO[0000] using database config /var/lib/drone/drone.sqlite
FATA[0000] unknown remote driver
```
since REMOTE_DRIVER wasn't set. I looked at the Load function in remote.go:
```
func Load(env envconfig.Env) Remote {
	driver := env.Get("REMOTE_DRIVER")

	switch driver {
	case "bitbucket":
		return bitbucket.Load(env)
	case "github":
		return github.Load(env)
	case "gitlab":
		return gitlab.Load(env)
	case "gogs":
		return gogs.Load(env)

	default:
		log.Fatalf("unknown remote driver %s", driver)
	}

	return nil
}
```
Perhaps there should first be a check done whether REMOTE_DRIVER has been set, and if not, print an error message suggesting the user ought to do so.

**Comment by johnrengelman** [comment] 2015-11-04 19:35
I got this same error on the 0.4 container even when sending `-v /var/lib/drone:/var/lib/drone` to the container with a previous DB existing there. Still investigating.

**Comment by bradrydzewski** [comment] 2015-11-04 19:36
@johnrengelman is the previous database an 0.3 database? I ask because the 0.4 database is not backward compatible with 0.3

**Comment by johnrengelman** [comment] 2015-11-04 19:37
I don't believe so...I was running the `drone/drone:latest` image from 6 weeks ago when I created it.

**Comment by bradrydzewski** [comment] 2015-11-04 19:40
@johnrengelman six weeks ago `drone/drone:latest` would have been running drone 0.3

**Comment by johnrengelman** [comment] 2015-11-04 19:42
ah, ok. So my option is to start over, correct? No migration path?

**Comment by bradrydzewski** [comment] 2015-11-04 19:44
correct, the changes from 0.3 to 0.4 were major. This also includes incompatible changes to the yaml to enable plugins and matrix builds.

**Comment by johnrengelman** [comment] 2015-11-04 19:46
Good deal. Thanks. Ignore my comments then ;)

**Comment by bndw** [comment] 2015-12-10 05:56
I'm getting the `unknown remote driver` error when following the example [in the docs](http://readme.drone.io/setup/). I'm assuming it's because I have an empty `dronerc`. Could you provide an example `dronerc`? I couldn't find one in the docs.

Here's my run command:
```
docker run \                                                                                                                    
        --volume /Users/me/Desktop/drone:/var/lib/drone \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --env-file /Users/me/Desktop/dronerc \
        --restart=always \
        --publish=8000:8000 \
        --detach=true \
        --name=drone \
drone/drone:0.4
```

 As a side note, do you plan to offer an upgrade path, or do you expect to have breaking changes on releases for a while?

**Comment by meowy** [comment] 2015-12-10 06:04
@bndw I'm trying out Drone myself in this very moment and stumbled across the same issue.

**Comment by meowy** [comment] 2015-12-10 06:11
@bndw I figured it out, you have to set up one of the four remotes, for instance, the [GitHub](http://readme.drone.io/setup/github.html) remote. Add the given environment variables, making sure to add the GitHub client ID and secret which you get when [creating a GitHub application](https://github.com/settings/developers).

**Comment by tboerger** [comment] 2015-12-10 06:28
@bndw you can see an example at https://github.com/drone/drone/blob/master/contrib/debian/drone/etc/drone/dronerc but you should drop the quotes as those are unsupported for docker env files. You should add the client id and the client secret directly to the REMOTE_CONFIG. Those variables are spread accross the install section of the linked documentation.

**Comment by bradrydzewski** [comment] 2015-12-10 07:53
the `--env-file` format is a simple `KEY=VALUE` format for feeding environment variables to Docker. It is the same as passing `-e KEY=VALUE -e KEY2=VALUE2` to Docker via the command line.

an example file would look like this:

```
KEY=VALUE
KEY2=VALUE2
```

The values in this file depend on how you would like to configure drone, the database type and remote system you would like to integrate with. If you choose GitHub integration, for example, you should add the environment variables specified in the GitHub documentation @ http://readme.drone.io/setup/github.html

**Comment by bndw** [comment] 2015-12-10 16:10
@meowy @tboerger @bradrydzewski Thanks for the help!

**Comment by bradrydzewski** [comment] 2016-02-16 16:39
It is also possible the host machine SELinux can have problems with mounting volumes. There was someone in the Gitter channel that had this same error message and was able to solve with the following:

> Yup, that was it. Workaround: mount a directory with the following: --volume /var/lib/drone:/var/lib/drone:z
(for reference http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/)

I'm going to close this issue because inability to connect tends to be configuration related, most of the time, or caused by certain edge cases related to the host machine configuration. There are otherwise no known issues with the sqlite implementation in drone.

**Closed by bradrydzewski** 2016-02-16 16:39 UTC
