### ISSUE TITLE
Github oauth received empty access token

### ISSUE THREAD

**Issue by Tuxity** [drone/drone#1435] opened 2016-01-25 18:48 UTC
Hi,

I'm trying to setup a drone app on a server and I have a problem with the github oauth i don't understand why:

In the page http://mydomain:8000/login
`
We failed to authorize your account. Please contact yoursystem administrator to check the logs and see what went wrong.
`

```
# docker logs drone
[GIN] 2016/01/25 - 18:38:40 | 303 |      73.647µs | xxx.xxx.xxx.xxx:54231 |   GET     /authorize
time="2016-01-25T18:38:40Z" level=error msg="cannot authenticate user. Error exchanging token. received empty access token from authorization server" 
[GIN] 2016/01/25 - 18:38:40 | 303 |  387.992285ms | xxx.xxx.xxx.xxx:54231 |   GET     /authorize
[GIN] 2016/01/25 - 18:38:41 | 200 |      67.608µs | xxx.xxx.xxx.xxx:54231 |   GET     /login
```

In github app the callback url is `http://mydomain:8000/authorize` and in the list of apps in my github user profile I've that app.

```
# cat /etc/drone/dronerc 
REMOTE_DRIVER=github
REMOTE_CONFIG=https://github.com?client_id=MYCLIENTID&client_secret=MYSECRETKEY&open=true
```

Thank

**Comment by bradrydzewski** [comment] 2016-01-25 18:57
this is failing at the oauth2 level to exchange a token with drone:
https://github.com/drone/drone/blob/master/remote/github/github.go#L104

there are no known oauth / login issues which means this is likely a configuration issue. While it is difficult to pinpoint exact root cause, what we know is that the http request from drone to github (to exchange the token) is failing. Are there any networking issues on your host machine? http proxies?

**Comment by Tuxity** [comment] 2016-01-25 19:01
No there is no such thing, I don't really understand where is the problem and how I can solve it.

**Comment by bradrydzewski** [comment] 2016-01-25 19:10
we've seen this error when there were configuration errors. Search for "received empty access token from authorization server" in the below thread as an example:
https://gitter.im/drone/drone/archives/2015/12/28

**Comment by Tuxity** [comment] 2016-01-25 20:47
I've checked again the envfile and I don't see any `?` `&` mistakes

```
DEBUG=true
#SERVER_ADDR=":8000"

CLIENT=XXXXXXXX
SECRET=XXXXXXXXX

REMOTE_DRIVER=github
#REMOTE_CONFIG=https://github.com?client_id=${CLIENT}&client_secret=${SECRET}&open=true
REMOTE_CONFIG=https://github.com?client_id=XXXXXXX&client_secret=XXXXXXXX&open=true
```

Here the configuration file I've actually. For some reason the var CLIENT isn't replaced, I just put the client id and client secret directly in the url, seem to work too.

Yes, I'm aware I've to destroy the container each time I change that file, I do that every time don't worry :)

That's weird because it's almost good. Github ask me if I authorize the app to access my account informations, I say yes and I go back to the login page with the error message.

**Comment by bradrydzewski** [comment] 2016-01-25 20:50
this is because the docker `--env-file` is a simple `KEY=VALUE` file. It is not a bash file and does not support string interpolation which means `${CLIENT}` will not work.

**Comment by Tuxity** [comment] 2016-01-26 16:25
I asked someone in my organization to test if he can login to the drone app aaaaand he can. So it's something related to my account I guess, maybe 2FA ?

**Comment by bradrydzewski** [comment] 2016-01-26 18:15
@Tuxity now that you've removed the interpolation from the `--env-file` do you still get the same error message in the logs? In GitHub what does your authorization screen look like for Drone in your user settings screen? (screenshot below) Make sure Drone is correctly authorized.

Also make sure you don't have any non-default or overly strict browser settings that might prevent GitHub or Drone from creating cookies. We've seen this in the past at https://github.com/drone/drone/issues/663

2FA should not impact the OAuth2 workflow from the Drone perspective. Drone redirects you to login and GitHub redirects back with a code that we exchange for a token. Any additional login steps (such as 2FA) are completely opaque to Drone and handle within GitHub login flow.

---

<img width="734" alt="screen shot 2016-01-26 at 10 05 50 am" src="https://cloud.githubusercontent.com/assets/817538/12589852/ad8fd33e-c414-11e5-9f7a-bef459a290cc.png">

**Comment by Tuxity** [comment] 2016-01-26 20:24
Yes, I still get the same error message.
I've the same page as you, the app have access to the organization and correct permission access

**Comment by bradrydzewski** [comment] 2016-01-26 20:30
What about restrictions at your organization level?
<img width="845" alt="screen shot 2016-01-26 at 12 26 41 pm" src="https://cloud.githubusercontent.com/assets/817538/12593878/25c7c6fa-c428-11e5-9145-7dc8a6737025.png">

Perhaps it makes sense to contact GitHub support and see if they can look at their logs and determine why the access token is not being returned from an authorization request? The fact that it works for your colleague but not for your account is also interesting.

Drone has a pretty mature authorization implementation and is used by a large number of developers. The fact that this seems to be a very isolated incident (to just your account) leads me to believe it might make sense to get GitHub involved.

**Comment by Tuxity** [comment] 2016-01-26 20:34
Same as your screenshot. You're right I'm gonna contact them and update the ticket.

**Comment by Tuxity** [comment] 2016-01-27 16:07
Well, some news. In fact it doesn't work too for my colleage... 

If I check the chrome developer console, after authorizing the app in the github page I see that:

```
http://mydomain.com:8000/authorize
https://github.com/login/oauth/authorize?client_id=XXXXXXXXXX&redirect_uri=http%3A%2F%2Fmydomain.com%3A8000%2Fauthorize&response_type=code&scope=repo%2Crepo%3Astatus%2Cuser%3Aemail&state=XXXXXXXXX%3D%3D%3D%3D
http://mydomain.com:8000/authorize?code=XXXXXXXX&state=XXXXXXXXX%3D%3D%3D%3D
http://mydomain.com:8000/login?error=oauth_error
```

Another question, I don't use a reverse proxy, it's not bad if I directly use :8000 instead ?

**Comment by Tuxity** [comment] 2016-03-03 00:53
@bradrydzewski according to #1466 should I try to install drone manually and not by pulling docker image too ?

**Comment by bradrydzewski** [comment] 2016-03-03 01:27
@Tuxity sorry but I'm not sure I'll be much help here. This issue seems to be network related and isolated to a very small number of installations, which makes it very difficult to troubleshoot and debug on my end

**Comment by Tuxity** [comment] 2016-03-03 01:29
Okay, well, what can I do to help you with that ?

Can you add some tags in the docker hub also please ? I would like to try with an older version like 3.1

**Comment by Tuxity** [comment] 2016-03-03 01:41
NEWS !!

I've done a new github oauth app, updated the new client id and client secret in `/etc/drone/dronerc` and it work 😱🤔 I guess something went wrong with github before when I've created the first app...

**Comment by bradrydzewski** [comment] 2016-03-03 07:15
wow, glad to hear that fixed the issue! perhaps it was something with GitHub. I'm going to close this under the assumption that the problem is gone, but we can re-open if it re-surfaces

**Closed by bradrydzewski** 2016-03-03 07:15 UTC

**Comment by johnrengelman** [comment] 2016-05-11 22:08
Just to add some comments...I've seen this issue a number of times. Have never been able to track it down. Unfortunately for this particular organization, I don't have admin access to to the org to create tokens, so I'm not sure if it's something the IT people or not.
Currently fighting it right now on a new install, so I'll post if I discover anything more.

**Comment by johnrengelman** [comment] 2016-05-11 22:15
And this time it was a hidden white space in the `REMOTE_CONFIG` envvar for the client secret...so it was a configuration issue.
