### ISSUE TITLE
git One push, but always multi pipeline run, why???

### ISSUE THREAD

**Issue by sunvooker** [drone/drone#2360] opened 2018-03-02 09:50 UTC
I build drone with gogs, but when i push code , the drone create multi pipeline run , why??

![image](https://user-images.githubusercontent.com/13518194/36893225-2e3d7be2-1e42-11e8-9fab-7cc4d188ab61.png)

**Comment by bradrydzewski** [comment] 2018-03-02 15:49
duplicate of https://github.com/drone/drone/issues/2094

**Closed by bradrydzewski** 2018-03-02 15:49 UTC
