### ISSUE TITLE
Drone doesn't schedule pods according to platform

### ISSUE THREAD

**Issue by ahmedmagdiosman** [drone/drone#2816] opened 2019-09-04 21:52 UTC
* Drone version: 1.3.1
* Mixed-arch K8s cluster
* Deployed using helm chart  https://github.com/helm/charts/tree/master/stable/drone

It seems drone randomly creates pods without taking into consideration the node's architecture. More often than not, AMD64 pipelines get scheduled on ARM64 nodes.

Here's my drone.yml

````
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: docker  
  image: plugins/docker
  pull: always
  settings:
    repo: example.com/firefly-iii
    registry: example.com
    auto_tag: true
    auto_tag_suffix: linux-amd64
    debug: true
    dockerfile: Dockerfile
---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: docker  
  image: plugins/docker
  pull: always
  settings:
    repo: example.com/firefly-iii
    registry: example.com
    auto_tag: true
    auto_tag_suffix: linux-arm64
    debug: true
    dockerfile: Dockerfile.arm64
---
kind: pipeline
name: manifest

steps:
- name: manifest
  image: example.com/drone-manifest
  pull: always
  settings:
    repo: example.com/firefly-iii
    registry: example.com
    ignore_missing: true
    spec: manifest.tmpl
    dump: true

trigger:
  event:
  - push
  - tag

depends_on:
- amd64
- arm64
````

Any idea what might be causing this? Thanks :)

**Comment by bradrydzewski** [comment] 2019-09-04 21:55
duplicate of https://github.com/drone/drone-runtime/issues/68

**Closed by bradrydzewski** 2019-09-04 21:55 UTC
