### ISSUE TITLE
Allow Drone to scheduled builds

### ISSUE THREAD

**Issue by DblK** [drone/drone#2111] opened 2017-07-12 16:54 UTC
I would like to have the opportunity to schedule a build let's say every night to build a canary version a release it.

This feature should be something like cron job with timezone and target a branch.
I would like also to be able to have severals schedule builds.

**Comment by bradrydzewski** [comment] 2017-07-12 16:55
duplicate of https://github.com/drone/drone/issues/1525 and https://github.com/drone/drone/issues/287

also see http://readme.drone.io/questions/how-to-schedule-builds/

**Closed by bradrydzewski** 2017-07-12 16:55 UTC

**Comment by tcarreon** [comment] 2019-04-11 18:21
link

> duplicate of #1525 and #287
> 
> also see http://readme.drone.io/questions/how-to-schedule-builds/

link is broken - Page Not Found

**Comment by bradrydzewski** [comment] 2019-04-11 18:23
That link is outdated which is why it was removed. Drone 1.0 has native cron capabilities. Go to your repository settings screen and you will see options to schedule cron jobs, including a nightly option.

**Comment by twpedersen** [comment] 2020-01-25 08:22
The cron scheduler does not seem to respect the TZ environment variable, so the "daily" schedule ends up being "midnight at UTC", is this expected?

Alternately, the drone cron cli could support https://godoc.org/github.com/robfig/cron#hdr-Time_zones:

$ drone cron add <repo> nightly "CRON_TZ=America/Los_Angeles 0 0 0 * * *"
client error 400: {"message":"Invalid Cronjob Expression"}

**Comment by bradrydzewski** [comment] 2020-01-25 18:45
> The cron scheduler does not seem to respect the TZ environment variable, so the "daily" schedule ends up being "midnight at UTC", is this expected?

Yes, this is the expected behavior since Drone uses unix timestamps and UTC times throughout the codebase. The ability to handle different timezeones was considered out of scope for our initial cron implementation. 

> Alternately, the drone cron cli could support https://godoc.org/github.com/robfig/cron#hdr-Time_zones:

We do not use the Cron scheduler in this package (nor do we want to). We only use the cron expression parser which, as far as I can tell, does not let you provide timezones. This is something we would have to handle manually, I suspect.

**Comment by bradrydzewski** [comment] 2020-01-25 19:06
__UPDATE__

I did some more research and it looks like the CRON_TZ feature was added to this library a few months _after_ we implemented cron in Drone. We are using a snapshot of the library from May 2018 and the CRON_TZ feature was added in Feb 2019. Updating to a newer version of the library may allow you to take advantage of CRON_TZ without any code changes to Drone itself.

**Comment by twpedersen** [comment] 2020-01-27 18:26
@bradrydzewski thanks for the response! I'll try to give this a go if time allows.
