### ISSUE TITLE
Follow in Firefox doesn't follow the log output

### ISSUE THREAD

**Issue by mprasil** [drone/drone#2179] opened 2017-08-25 15:23 UTC
When I enable following in Firefox while the job is running, browser doesn't follow the log output - in fact instead of scrolling to the end of the stream, it seems so "jump" to the top of the page. 

Drone 0.8.0-rc3
Firefox 55.0.2

All works as expected in Chromium

**Comment by bradrydzewski** [comment] 2017-08-25 15:25
duplicate of https://github.com/drone/drone-ui/issues/140

**Closed by bradrydzewski** 2017-08-25 15:25 UTC

**Comment by mprasil** [comment] 2017-08-25 15:27
Apologies for that @bradrydzewski, do we report all UI bugs under drone-ui?
