### ISSUE TITLE
Any plan to support tag_push_event of gitlab?

### ISSUE THREAD

**Issue by depay** [drone/drone#1117] opened 2015-08-03 01:41 UTC
As we wanna trigger some action by gitlab tag event, e.g. building&pushing docker image,  tag_push_event supporting is required. 

i've submit a PR in Bugagazavr/go-gitlab-client to support tag_push_event by go-gitlab-client. https://github.com/Bugagazavr/go-gitlab-client/pull/11

**Comment by bradrydzewski** [comment] 2015-08-03 02:38
Yes, I started laying the groundwork in the next release for such a feature. I've added the ability to enable a repository to build tags (similar to pull requests and pushes):
https://github.com/drone/drone/blob/0.4-database/pkg/types/repo.go#L60:L64

I've also updated the git plugin to fetch refs, which enables tags:
https://github.com/drone-plugins/drone-git/blob/master/main.go#L139:L146

I've also removed database restrictions that exist in 0.3 (current stable) that prevent this feature.

In addition to the above changes, we'll need the ability to restrict publish and deploy steps to tags. We'll need to alter the `Condition` structure which exposes conditional logic in the yaml:
https://github.com/drone-plugins/drone-git/blob/master/main.go#L139:L146

Second, each plugin (GitHub, Bitbucket, etc) needs the ability to enable tag hooks. I believe this is already the case with GitHub, but we'll need to do the same with other systems.

Third, each plugin needs to be able to correctly parse the hooks and convert to a build object. This will need to be implemented for each as well.

And last, we'll need to add a toggle to the user interface to enable / disable executing builds for tags. I believe it should be off by default, and something that can be manually enabled in the repository settings screen.

This isn't an immediate priority for me since I'm still trying to get a working version of 0.4 release before adding new features, but those are the required steps if anyone wants to jump in and start enabling this feature :)

**Comment by depay** [comment] 2015-08-03 02:50
thanks @bradrydzewski . i'll do something on it, as it seems immediate for me lol.

**Comment by bradrydzewski** [comment] 2015-08-03 02:53
help is much appreciated :)  please know, however, that `0.4-database` is not yet functional and there is quite a bit more work required to push a beta release

**Comment by bradrydzewski** [comment] 2015-08-18 19:56
dupe of #468

**Closed by bradrydzewski** 2015-08-18 19:56 UTC
Labels: started

**Comment by os12** [comment] 2016-01-05 21:40
Hi Brad, how far did #1130 go?

The use case I have in mind may be a little simpler than a custom "tag recipe":
  1. [Human] creates an annotated tag
  1. [Human] pushes the tag to GitHub
  1. [Drone] starts a normal build
    1. detect that the build is related to a tag
    1. perform a normal build
    1. do some extra steps when tagging (eg: publish the artifacts)

Is this possible today?

Thanks!

**Comment by bradrydzewski** [comment] 2016-01-05 21:44
@os12 yes, in your repository settings in drone enable tags (via the toggle). Then in your `.drone.yml` file you can mark specific publish or deployment tasks for tags. See http://readme.drone.io/usage/deploy/#conditions:0814af543608f4fd171b2e9cf43d9917

**Comment by os12** [comment] 2016-01-05 23:48
Thanks, Brad! Could you clarify the following please:
  1. Did the patch make it into 0.4.0?
  1. It it possible to invoke a script from the `publish:` section?
    * the vm/container is already configured with Google Cloud Storage access and has the official tools
    * is there a "shell" plugin?

**Comment by bradrydzewski** [comment] 2016-01-06 00:10
> Did the patch make it into 0.4.0?

Yes

> It it possible to invoke a script from the publish: section?

No, this is not possible without a custom plugin

Instead I would recommend reading more about multiple build steps. You could create multiple build steps, and make one of the steps conditional to only execute for tags. Furthermore, steps don't execute if preceding steps fail.

You can read more about it here:
http://readme.drone.io/usage/build_test/#conditions:fb92aa3346185c57f15afda861d465a3

Even though the step is in the build section, it will behave almost identically to a step in the publish or deploy section when proper conditions are applied.

> is there a "shell" plugin?

No, there is no official shell plugin.

This is because plugins run in their own isolated containers and as a result, there is no way for us to provide a generic shell image that would meet the requirements of most teams (OS, installed software, etc).

You can always create and white-list your own shell plugin. This is an example of someone that has done something similar: https://github.com/crhym3/drone-plugin-bash
