### ISSUE TITLE
Ability to delete logs (in case you accidentally expose a password in your logs)

### ISSUE THREAD

**Issue by wrouesnel** [drone/drone#1584] opened 2016-04-20 05:13 UTC
Drone should implement some basic log parsing for the web UI so secret exposure can be fail-safed.

This would be implemented by treating specified secrets as an array of "do not print" words, and scrubbing them from the log output.

While there is an obvious vector here of weak-passwords being highlighted by emitted text, this is marginal compared to the benefits of "failing safe" for the common case, and could be mitigated by assigning secrets as "fail if appears in logs" by default (which you should never really need to turn off).

**Comment by bradrydzewski** [comment] 2016-04-20 06:08
This is an interesting idea and I'm not opposed. This brings up an interesting vector though. What if I send a pull request that `cat`'s a file of common passwords to see what drone scrubs to try to identify passwords?

**Comment by bradrydzewski** [comment] 2016-04-20 06:13
@nlf wondering if you had any thoughts from a security perspective. How can we help prevent someone from exposing secrets in the logs without creating a potential vector for exposing passwords? (see my prior comment)

**Comment by wrouesnel** [comment] 2016-04-20 06:40
A good initial step might just be have a notification path for repository owners to be notified when the log output *contains* a password? That provides a decent heads up, without the complications of trying to handle arbitrary input.

The only thing I can think of for the PR case is to set up a variable sized delay buffer on the log streams so when you detect a password, you blank out a varying amount of text in the output so it's harder to bruteforce. Ratelimiting PRs from accounts which have triggered protection would also help here.

**Comment by wrouesnel** [comment] 2016-04-20 07:11
Ok so a quick test, secrets are available to forked PRs with Github which is a problem. Travis solves this by not decrypting on forks. Should this be raised as a separate issue?

**Comment by bradrydzewski** [comment] 2016-04-20 07:14
> Ok so a quick test, secrets are available to forked PRs with Github which is a problem. Travis solves this by not decrypting on forks. Should this be raised as a separate issue?

no, this is the desired behavior and is documented appropriately with a large warning at the top of the documentation at http://readme.drone.io/usage/secrets/ with suggested workarounds for including secrets in the build section at http://readme.drone.io/usage/secrets/#pull-requests:0d943d142dc6bcdd2e544b095a49f72b

**Comment by steve-gray** [comment] 2016-05-06 21:16
All of the stuff being talked about here ignores a few basics:

- Filtering out the password is easy enough - but what if I just do string.reverse() and print it? Whups.
- curl the files out somewhere else.

Trouble is that if we just block access to the build log display for anyone non-authorized, a few lines of code in the PR that runs during the unit tests could easily just curl out the entire process.env block to any destination.

How about:

- Scoped secrets: Ability to specify a when: on a secret so I can say that my secret is only available in a 'tag' on 'master'.
- Phase-scoped secrets: Ability to scope secrets to only be available at various phases (i.e. deploy, notify)

These would prevent errant code from seeing things like Dockerhub/NPM/Gem credentials, blocks any process from actually trying to scrape them during build (you can't steal it if it's not there).

For things like databases people depend on during build, unfortunately the only way to really secure that stuff is to make those instances ephemeral during the compose phase and not rely on well-known passwords in the build process.

**Comment by bradrydzewski** [comment] 2016-05-06 22:21
@steve-gray agreed, scoped secrets are coming to 0.5. Yuo can read more about the proposal and implementation, which has already landed in master, at https://github.com/drone/drone/issues/1538#issuecomment-201403419

The changes to 0.5 make it much more difficult to leak secrets. In addition to the above change, secrets are now injected as environment variables instead of yaml interpolation which prevents them from being interpolated into a build command and output in the logs.

Sanitizing logs sounds good in theory but in practice I have to consider:

1. it provides a vector to discover passwords (cat dictionary.txt and see what drone sanitizes) 
2. it isn't full proof
3. it has performance implications
4. it is much more difficult to leak secrets in 0.5

The likely solution to this issue will be providing a way to scrub the logs when something is accidentally output that shouldn't be. I'm updating the title of this issue to reflect the proposed solution.

**Comment by steve-gray** [comment] 2016-05-06 23:10
I wouldn't even bother with the hiding of the password in the output logs. I seriously would have gone utterly batshit trying to figure out a problem I had earlier today (drone secret with ! in the string, causing bash command to die with a random error) if I wasn't able to just echo out the raw bash command and then re-run it on my local machine.

If you hide the passwords, it'll imply this has got some _real_ security and not just an illusion of security. My vote goes for more ominous, potentially red, text on the secrets information page ;)

Scoping fixes the real problem, and that change in 0.5 looks awesome. I'm just not prepared to tick the FIX_BUGS_DONT_FILE_BUGS box *just* yet.

**Comment by bradrydzewski** [comment] 2016-05-06 23:14
sorry I chose poor wording in my prior comment ... what I meant by "scrub" or "purge" the logs is to delete them completely if you accidentally output something sensitive. I have no intention of implementing sanitization at this time. I edited my prior comment to remove ambiguity.

**Comment by steve-gray** [comment] 2016-05-06 23:48
Ahh, so the user can choose to delete the logs rather than an outright: "If see password > purge()". That's a much cleaner idea 👍

**Comment by eploko** [comment] 2016-08-31 10:07
Travis CI does this in a bit different way, which, never the less, is quite thought through, I believe. For every environment variable there's a switch to either output or hide it from the logs. Could we add a field to the `.drone.yml` file that would, say, explicitly name the variable which values should be output and hide the rest otherwise. This will work fine for most of the cases, I reckon, including the one when one'd want to output a variable's value to debug the build.

![image](https://cloud.githubusercontent.com/assets/116603/18124586/2bb27292-6fb6-11e6-8f34-91be83d6e82e.png)

**Comment by steve-gray** [comment] 2016-08-31 10:48
I see several aspects of 0.5 that prevent this from being too much of a problem:

- Secrets are task-scoped now, so anyone who hacks around with your code can't make you echo your docker hub password - the password is only given to the docker plugin.
- Privileged containers don't seem to execute arbitrary commands by default (they have one job to do, and it doesnt involve arbitrary script)
- You can set what steps get executed on a pull request versus a push/tag/deploy.

In short, pretty much every avenue to get that secret echo'd out is closed off. The steps that recieve the secret are completely disjoint from the steps that run the user code for the build, and dont' by default run during a PR/build - preventing a malicious secret exposure in most cases - you'd have to allow secrets for untrusted code paths.

The Travis toggle, whilst well intentioned, is very naive in its implementation. If you had 'Password' as a secret, then someone did:

- echo User Password for %s is set to %s

You'd see 'User **** for name is set to *****' or somesuch. That gives the game away a bit. The 0.5 approach is somewhat more robust in this regard, but the ability to purge the logs for a specific build would be a good stopgap for anything that gets between the cracks.

**Comment by tboerger** [comment] 2016-08-31 12:55
If you don't want to print environment variables within commands just write $FOO instead of ${FOO}, than it gets evaluated and not printed to the log.

**Comment by vaijab** [comment] 2016-10-11 16:24
So I had a brief conversation with Brad on gitter. We agreed that obfuscating secrets in logs is a feature that is nice to have. There are certainly ways around the obfuscation, but what obfuscation solves is accidental exposure of secrets in logs.

I am happy to build this feature. By default secrets obfuscation in logs will be disabled. The question is, where do we add the feature flag? At repo level or agent level?

**Comment by vaijab** [comment] 2016-10-16 11:54
PR which implements an optional per-agent secrets concealer in build logs: https://github.com/drone/drone/pull/1816

**Comment by patrickjahns** [comment] 2016-11-07 21:02
Is is still possible to create a "purge build log" method?
Sometimes it might be handy to have a look at the environment variables for testing/debugging purposes and it would be great to afterward either purge the log of a build or completely remove a build?

**Comment by tonglil** [comment] 2017-08-17 15:44
I would like to second the "purge" after review feature. There seems to be two FRs in this issue :p

**Comment by bradrydzewski** [comment] 2018-01-17 19:52
Yes, I think we should add a `drone logs purge <repo> <number> <proc>` command and an API endpoint. It is easy to implement, and it gives us an immediate solution that people can use.

The new runtime in 0.9 enables masking single-line secrets by default, however, it is not possible to mask multi-line secrets. So if a multi-line secret it leaked in the logs, `drone logs purge` would still be useful.

**Comment by bradrydzewski** [comment] 2018-01-18 18:15
Closed by #2308

You can curl the endpoint to purge the logs:

```
curl -X DELETE -H "Authorization: Bearer XXXXXXXXXXXX" \
    https://ci.gogs.drone.io/api/repos/octocat/hello-world/logs/1 
```

We do not yet have a CLI command for this, however, the endpoint is available and I have confirmed that it is working properly.

**Closed by bradrydzewski** 2018-01-18 18:15 UTC

**Comment by iamface** [comment] 2020-04-19 22:16
This is a bit old, but the above command does not seem to work for me, I get a `404`.  I'm running 1.2.1 and I need to remove one log from a bad commit :/

**Comment by hkraal** [comment] 2021-01-09 21:18
For others ending up here the, check the docs at https://docs.drone.io/api/builds/build_logs/. On this moment of writing the correct URL is `DELETE /api/repos/{owner}/{repo}/builds/{build}/logs/{stage}/{step}`
