### ISSUE TITLE
Server<->Agent reliability causing new builds to stay Pending

### ISSUE THREAD

**Issue by prologic** [drone/drone#2270] opened 2017-11-24 20:08 UTC
I've been trying to get to the bottom of this for a while (*with no success*). This is probably also related to #2246 and there have been a few discussions on the Discourse forums. I am running the following setup via Docker:

```#!yaml
version: "3.3"

services:
  drone-server:
    image: drone/drone:latest
    environment:
      - DRONE_DEBUG=true
      - DRONE_OPEN=true
      - DRONE_HOST=https://ci.mydomain.com
      - DRONE_GOGS=true
      - DRONE_GOGS_PRIVATE_MODE=true
      - DRONE_GOGS_URL=https://git.mydomain.com  # running Gogits (0.11.29.0727)
      - DRONE_SECRET=###
      - DRONE_ADMIN=###
    networks:
      - drone
      - traefik
    volumes:
      - dronedata:/var/lib/drone
    deploy:
      placement:
        constraints:
          - "node.hostname == node1.mydomain.com"
      labels:
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.backend=ci"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host:ci.mydomain.com"
      restart_policy:
        condition: on-failure
      replicas: 1

  drone-agent:
    image: drone/agent:latest
    command: agent
    networks:
      - drone
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_DEBUG=true
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=###
    deploy:
      placement:
        constraints:
          - "node.role != manager"
      restart_policy:
        condition: on-failure
      replicas: 3

networks:
  drone:
    driver: overlay
  bridge:
    external: true
  traefik:
    external: true

volumes:
  dronedata:
    external: true
```

This is deploy with `docker stack` in a Swam Mode cluster:
```#!bash
$ docker stack deploy -c ci.yml ci
```

This works fine for a little while (~5-10mins?) and later when I think about pushing new commits to Gogits and want a CI build; I have to:

```#! bash
$ docker stack rm ci
$ docker stack deploy -c ci.yml ci
```

Effectively tearing down the entire CI and rebuilding it (*except its local data*).

To date I've not been able to gleam anything useful from the debug logs of either the server nor the agent(s).

This is the output of `drone build list`:

```#!bash
$ drone build list prologic/eris
Build #24
Status: pending
Event: push
Commit: 3a9d1fefc834d20991b784993589ed2cc558289c
Branch: master
Ref: refs/heads/master
Author: prologic <james@mydomain.com>
Message: Update README.md
```

**Comment by prologic** [comment] 2017-11-24 20:15
According to hitting the API I'm running:

`X-Drone-Version: 0.8.2+build.1348`

**Comment by bradrydzewski** [comment] 2017-11-24 20:44
Duplicate of #2246

**Comment by prologic** [comment] 2017-11-24 20:44
Oh it is? Cool! I'll have a full read (*the thread got a bit long for my poor eyes!*)

**Closed by bradrydzewski** 2017-11-24 20:44 UTC

**Comment by prologic** [comment] 2017-11-24 20:46
Hold on! @bradrydzewski  I'm a little confused:

> Until we have a patch, it is not recommended to route agent communication through a load balancer or reverse proxy. When I start working on this I will update the issue status, but in the meantime, please feel free to send a patch if you want to expedite a resolution to this issue.

I'm 99% sure this is not the case with how I'm deploying Drone here. Can we re-look at this?

**Comment by prologic** [comment] 2017-11-24 20:47
Specifically this line in my `ci.yml` sack:

```
      - DRONE_SERVER=drone-server:9000
```

*Should* be connecting directly via the overlay network / discovery via its service name "drone-server"

**Comment by bradrydzewski** [comment] 2017-11-24 20:48
Can you provide any sort of error messages, logging, etc? There is not really anything actionable I can use to debug this further. We have a few thousand 0.8 installs and there are no reports of networking issues, aside from when you route the communications through a reverse proxy or load balancer.

**Comment by prologic** [comment] 2017-11-24 20:50
Sure; but what am I looking for in the server/agent logs? I can grep them
if I know what to look for.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by bradrydzewski** [comment] 2017-11-24 20:52
> I'm 99% sure this is not the case with how I'm deploying Drone here. Can we re-look at this?

Also have you tried to reproduce this without using an overlay network? There seem to be documented issues with overlays.

* https://github.com/moby/moby/issues/32738
* https://github.com/moby/moby/issues/32195

**Comment by prologic** [comment] 2017-11-24 20:54
The only other thing I can try to rlue out is to change the deployment `endpoint_mode` to `dnsrr`

The docs:

> ENDPOINT_MODE
> 
> Specify a service discovery method for external clients connecting to a swarm.
> 
> Version 3.3 only.
> endpoint_mode: vip - Docker assigns the service a virtual IP (VIP), which acts as the “front end” for clients to reach the service on a network. Docker routes requests between the client and available worker nodes for the service, without client knowledge of how many nodes are participating in the service or their IP addresses or ports. (This is the default.)
> 
> endpoint_mode: dnsrr - DNS round-robin (DNSRR) service discovery does not use a single virtual IP. Docker sets up DNS entries for the service such that a DNS query for the service name returns a list of IP addresses, and the client connects directly to one of these. DNS round-robin is useful in cases where you want to use your own load balancer, or for Hybrid Windows and Linux applications.

However this doesn't make a terrible lot of sense since it talks about "external clients" and mentions nothing about internal behavior between containers across a swarm overlay.

**Comment by bradrydzewski** [comment] 2017-11-24 20:57
the main difference between your sample configuration, and the default configuration being used by the majority of production installations, is the overlay network. I am finding many open issues in the moby issue tracker for overlay networks, including some related to GRPC. So this seems like the best place to start.

**Comment by prologic** [comment] 2017-11-24 20:57
So what you're saying is you have thousands of 0.8 instances running without Docker's overlay :)
(*Why didn't you say that before! :P*) -- It's okay to blame overlay here; I've seen some weird things myself that a restart fixes.

I'll see if changing the `endpoint_mode` helps at all; otherwise I'll runthe server and agents outside of an overlay network.

**Comment by prologic** [comment] 2017-11-24 21:05
For those that come across this; here's my modified `ci.yml` (*Docker Stack*) that I'm hoping will work (*so far so good; everything is connecting, 1 build going so far*):

```#!yaml
version: "3.3"

services:
  drone-server:
    image: drone/drone:latest
    ports:
      - "10.0.0.10:9000:9000/tcp"
    environment:
      - DRONE_DEBUG=true
      - DRONE_OPEN=true
      - DRONE_HOST=https://ci.mydomain.com
      - DRONE_GOGS=true
      - DRONE_GOGS_PRIVATE_MODE=true
      - DRONE_GOGS_URL=https://git.mydomain.com
      - DRONE_SECRET=###
      - DRONE_ADMIN=###
    networks:
      - traefik
    volumes:
      - dronedata:/var/lib/drone
    deploy:
      placement:
        constraints:
          - "node.hostname == node1.mydomain.com"
      labels:
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.backend=ci"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host:ci.mydomain.com"
      restart_policy:
        condition: on-failure
      replicas: 1

  drone-agent:
    image: drone/agent:latest
    command: agent
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_DEBUG=true
      - DRONE_SERVER=10.0.0.10:9000
      - DRONE_SECRET=###
    deploy:
      placement:
        constraints:
          - "node.role != manager"
      restart_policy:
        condition: on-failure
      replicas: 3

networks:
  bridge:
    external: true
  traefik:
    external: true

volumes:
  dronedata:
    external: true
```

Where `node1`'s internal IP is `10.0.0.10` -- Basically side-stepping overlay networking issues.

**Comment by prologic** [comment] 2017-11-25 06:32
So sadly even by-passing the overlay networking here and connecting directly has l't helped :/

**Comment by tboerger** [comment] 2017-11-25 07:51
I had the same issue for my swarm deployment, but since I have not been able to gather any useful debugging information I deployed drone via plain docker-compose instead of a stack :(

**Comment by JaredReisinger** [comment] 2018-05-06 09:58
I had the same problem with a swarm-based deployment, and setting the `deploy.endpoint_mode` to `dnsrr` _did_ seem to fix the problem.  In my stack YAML, I did:

```yaml
  server:
    # . . .
    deploy:
      endpoint_mode: dnsrr

  agent:
    # . . .
    deploy:
      endpoint_mode: dnsrr
```

Setting the mode for both server and agent might be overkill, but things seem to be working.

**Comment by OmgImAlexis** [comment] 2018-05-06 22:32
@JaredReisinger same for me. Not adding it to both still caused dropouts for me.
